# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Voidforge

from .. import *
from .. import Camera
from .. import Point
from .. import Target

@UTTCGen
class Agent(MonoBehaviour):
	pass
@UTTCGen
class AgentCollection(MonoBehaviour):
	pass
@UTTCGen
class AssetAttribute(MonoBehaviour):
	pass
@UTTCGen
class BaseParameter(MonoBehaviour):
	pass
@UTTCGen
class BitArray32(MonoBehaviour):
	bits : int
@UTTCGen
class CameraExtensions(MonoBehaviour):
	pass
@UTTCGen
class CameraShaker(MonoBehaviour):
	rpm : float
	maxAngle : float
	cameras : List[Camera]
@UTTCGen
class CameraTrackingTag(MonoBehaviour):
	Camera : List[Camera]
@UTTCGen
class ChineseRichTextParser(MonoBehaviour):
	pass
@UTTCGen
class ColorConversion(MonoBehaviour):
	pass
@UTTCGen
class ComponentExtensions(MonoBehaviour):
	pass
@UTTCGen
class ComponentInstancePool_1(MonoBehaviour):
	maxSize : int
@UTTCGen
class ComponentRef_1(MonoBehaviour):
	pass
@UTTCGen
class ComponentRegistry_1(MonoBehaviour):
	pass
@UTTCGen
class ComponentRegistry_2(MonoBehaviour):
	pass
@UTTCGen
class DSP_1(MonoBehaviour):
	pass
@UTTCGen
class Ease(MonoBehaviour):
	pass
@UTTCGen
class FixedUpdateAttribute(MonoBehaviour):
	pass
@UTTCGen
class GetComponentAttribute(MonoBehaviour):
	pass
@UTTCGen
class HotkeyHandler(MonoBehaviour):
	hotkey : int
@UTTCGen
class HotkeyPriorityHandler(MonoBehaviour):
	hotkey : int
	priority : int
@UTTCGen
class IComponentRef(MonoBehaviour):
	pass
@UTTCGen
class ICursorSource(MonoBehaviour):
	pass
@UTTCGen
class IdTag(MonoBehaviour):
	id : str
@UTTCGen
class InputAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputAxisAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputAxisRawAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputButtonAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputConditionsAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputEventDataAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputKeyAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputKeyFromFuncAttribute(MonoBehaviour):
	pass
@UTTCGen
class InputManager(MonoBehaviour):
	pass
@UTTCGen
class InputPointer(MonoBehaviour):
	pass
@UTTCGen
class InputTriggerAttribute(MonoBehaviour):
	pass
@UTTCGen
class InstanceFactory(MonoBehaviour):
	pass
@UTTCGen
class InstanceKeeperTag_1(MonoBehaviour):
	pass
@UTTCGen
class InstancePool(MonoBehaviour):
	maxSize : int
@UTTCGen
class InstancePoolForPrefab(MonoBehaviour):
	maxSize : int
	prefab : PPtr[Transform]
@UTTCGen
class InstancePoolTester(MonoBehaviour):
	count : int
@UTTCGen
class Int2(MonoBehaviour):
	x : int
	y : int
@UTTCGen
class LateUpdateAttribute(MonoBehaviour):
	pass
@UTTCGen
class LevelManager(MonoBehaviour):
	editorOnlyTag : str
	loadLevels : List[int]
	loadAsync : List[object] # XXX: Fallback of Boolean[]
@UTTCGen
class Line(MonoBehaviour):
	length : float
@UTTCGen
class MaterialKeeperTag(MonoBehaviour):
	pass
@UTTCGen
class MeshExtensions(MonoBehaviour):
	pass
@UTTCGen
class NavAreaMask(MonoBehaviour):
	value : int
@UTTCGen
class NavMeshPathTag(MonoBehaviour):
	pass
@UTTCGen
class NormalUpdateAttribute(MonoBehaviour):
	pass
@UTTCGen
class ObjectConversion(MonoBehaviour):
	pass
@UTTCGen
class ObservedAnimationCurve(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
@UTTCGen
class ObservedBool(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : bool
@UTTCGen
class ObservedBounds(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : object # XXX: Fallback of Bounds
@UTTCGen
class ObservedColor(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : ColorRGBA
@UTTCGen
class ObservedDouble(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : float
@UTTCGen
class ObservedFloat(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : float
@UTTCGen
class ObservedInt(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : int
@UTTCGen
class ObservedLong(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : int
@UTTCGen
class ObservedQuaternion(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : object # XXX: Fallback of Quaternion
@UTTCGen
class ObservedRect(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : object # XXX: Fallback of Rect
@UTTCGen
class ObservedString(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : str
@UTTCGen
class ObservedValue(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
@UTTCGen
class ObservedVector2(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : Vector2f
@UTTCGen
class ObservedVector3(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : Vector3f
@UTTCGen
class ObservedVector4(MonoBehaviour):
	_name : str
	_path : str
	_operations : int
	_value : Vector4f
@UTTCGen
class OnScreenTrackingTag(MonoBehaviour):
	viewCamera : PPtr[Camera]
	layerMask : object # XXX: Fallback of LayerMask
	perVertex : bool
@UTTCGen
class Operation(MonoBehaviour):
	value__ : int
@UTTCGen
class Path(MonoBehaviour):
	_isLoop : bool
	_points : List[Point]
@UTTCGen
class PathAsset(MonoBehaviour):
	_path : Path
@UTTCGen
class PathComponent(MonoBehaviour):
	_path : Path
@UTTCGen
class PersistentAttribute(MonoBehaviour):
	pass
@UTTCGen
class PhysicsUpdateAttribute(MonoBehaviour):
	pass
@UTTCGen
class PlayTween(MonoBehaviour):
	pass
@UTTCGen
class PositionTrackingTag(MonoBehaviour):
	pass
@UTTCGen
class PragmaAttribute(MonoBehaviour):
	pass
@UTTCGen
class PrioritizedActionList(MonoBehaviour):
	pass
@UTTCGen
class PrioritizedActionList_1(MonoBehaviour):
	pass
@UTTCGen
class PrioritizedList_1(MonoBehaviour):
	pass
@UTTCGen
class RichTextParser(MonoBehaviour):
	pass
@UTTCGen
class SingletonClass_1(MonoBehaviour):
	pass
@UTTCGen
class SingletonComponent_1(MonoBehaviour):
	pass
@UTTCGen
class SingletonScriptable_1(MonoBehaviour):
	pass
@UTTCGen
class SingletonScriptableBase(MonoBehaviour):
	pass
@UTTCGen
class TangentSpace(MonoBehaviour):
	pass
@UTTCGen
class TextInstancePool(MonoBehaviour):
	maxSize : int
	font : PPtr[Font]
@UTTCGen
class TextureKeeperTag(MonoBehaviour):
	pass
@UTTCGen
class Timer(MonoBehaviour):
	pass
@UTTCGen
class Triangle2D(MonoBehaviour):
	pass
@UTTCGen
class Tuple_3(MonoBehaviour):
	pass
@UTTCGen
class Tuple_4(MonoBehaviour):
	pass
@UTTCGen
class Tuple_5(MonoBehaviour):
	pass
@UTTCGen
class Tuple_6(MonoBehaviour):
	pass
@UTTCGen
class Tuple_7(MonoBehaviour):
	pass
@UTTCGen
class Tuple_8(MonoBehaviour):
	pass
@UTTCGen
class Tween(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
@UTTCGen
class TweenAddForce(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
	function : int
	force : Vector3f
	position : Vector3f
	mode : int
	_duration : float
@UTTCGen
class TweenAlpha(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
@UTTCGen
class TweenAnimation(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
	tweenAnimationClip : PPtr[AnimationClip]
	clipName : str
@UTTCGen
class TweenAudioSourceVolume(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
@UTTCGen
class TweenColor(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
	channelMask : int
@UTTCGen
class TweenController(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
	controlledTweens : List[Tween]
	getFromHierarchy : bool
	randomOrder : bool
	playSequentially : bool
	playType : int
	subsetSize : int
@UTTCGen
class TweenDeactivate(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
	destroyGameObject : bool
@UTTCGen
class TweenHue(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
@UTTCGen
class TweenShaderProperty(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
	propertyName : str
@UTTCGen
class TweenState(MonoBehaviour):
	value__ : int
@UTTCGen
class TweenTimeScale(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
@UTTCGen
class TweenTransform(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
	tweenPosition : bool
	position : Vector3f
	tweenRotation : bool
	rotation : Vector3f
	tweenScale : bool
	scale : Vector3f
	duration : float
@UTTCGen
class TweenValue_1(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
@UTTCGen
class UIDebugOnScreenTrackingTag(MonoBehaviour):
	target : PPtr[Transform]
@UTTCGen
class UITargetTracker(MonoBehaviour):
	target : PPtr[Transform]
@UTTCGen
class UITweenCanvasgroupAlpha(MonoBehaviour):
	description : str
	target : Target
	playOnStart : bool
	delayStart : float
	delayFinish : float
	playSpeed : float
	updateType : int
	ignoreTimeScale : bool
	onFinish : object # XXX: Fallback of UnityEvent
@UTTCGen
class UpdateAttribute(MonoBehaviour):
	pass
@UTTCGen
class UpdateManager(MonoBehaviour):
	gcCollectionInterval : float
@UTTCGen
class UpdateType(MonoBehaviour):
	value__ : int
@UTTCGen
class VectorExtensions(MonoBehaviour):
	pass
@UTTCGen
class VoidElement(MonoBehaviour):
	pass
@UTTCGen
class VoidTag(MonoBehaviour):
	pass
