# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for System.Runtime.CompilerServices

from .... import *

@UTTCGen
class IsReadOnlyAttribute(MonoBehaviour):
	pass
