# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages

from .. import *

@UTTCGen
class DestroyIfIOS(MonoBehaviour):
	pass
@UTTCGen
class DialogueBridgePages(MonoBehaviour):
	pass
@UTTCGen
class DisableIfPageUIIsNotRunning(MonoBehaviour):
	pass
@UTTCGen
class GameplayToPage(MonoBehaviour):
	pass
@UTTCGen
class HudToggleBridgeToPages(MonoBehaviour):
	pass
