# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.Gameplay.Dialogue

from .... import *
from .... import CheckAdvisor
from ....DiscoPages.Elements.Dialogue import ContinueResponseTogglePageSystem
from ....DiscoPages.Elements.Dialogue import ConversationLoggerPageSystem
from .... import LogRenderer
from .... import ScrollDown
from .... import SunshineContinueButton

@UTTCGen
class DialogueNavigationParameters(MonoBehaviour):
	conversationLogger : PPtr[ConversationLoggerPageSystem]
	dialogueSystem : PPtr[object] # XXX: Fallback of PPtr<DialogueSystemControllerPageSystem>
@UTTCGen
class DialoguePage(MonoBehaviour):
	minimizeButtons : List[object] # XXX: Fallback of Button[]
	dialoguePanel : PPtr[RectTransform]
	psContinueButton : PPtr[SunshineContinueButton]
	psScrollDown : PPtr[ScrollDown]
	psPortraitImg : PPtr[Image]
	psUnityUI : PPtr[object] # XXX: Fallback of PPtr<AbstractDialogueUI>
	psScrollController : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	psLogRenderer : PPtr[LogRenderer]
	psInteractionToggler : PPtr[ContinueResponseTogglePageSystem]
	fullscreenImageRect : PPtr[RectTransform]
@UTTCGen
class SkillcheckRollPage(MonoBehaviour):
	rollButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	goBackButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	advisor : PPtr[CheckAdvisor]
