# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Views

from ... import *
from ... import FeldSlide
from ... import HudController
from ... import HudMainMenuButtonTrigger
from ...Sunshine import Newspaper
from ... import SaveGameListEntryState
from ... import SoundPlayer
from ... import SplashScreenTabController
from ... import Text
from ... import VerticalStepScrollView

@UTTCGen
class ViewType(MonoBehaviour):
	value__ : int
@UTTCGen
class ActiveInView(MonoBehaviour):
	activeViews : List[ViewType]
@UTTCGen
class ArchetypeSelectionView(MonoBehaviour):
	hardcoreIcon : PPtr[GameObject]
@UTTCGen
class CharacterCreationAdjustAbilitiesView(MonoBehaviour):
	randomButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	revertAbilitiesButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	nextButton : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class CharacterCreationSetSkillView(MonoBehaviour):
	pass
@UTTCGen
class CharacterSheetView(MonoBehaviour):
	pass
@UTTCGen
class ClearView(MonoBehaviour):
	pass
@UTTCGen
class CollageModeView(MonoBehaviour):
	exitConfirmationTerm : str
@UTTCGen
class CutsceneView(MonoBehaviour):
	pass
@UTTCGen
class DialogueView(MonoBehaviour):
	pass
@UTTCGen
class HelpOverlayView(MonoBehaviour):
	pass
@UTTCGen
class HudToggle(MonoBehaviour):
	hudMainMenuButtonTrigger : PPtr[HudMainMenuButtonTrigger]
	target : PPtr[HudController]
	hudsToToActivate : List[GameObject]
@UTTCGen
class InventoryPawnView(MonoBehaviour):
	characterColumn : PPtr[RectTransform]
	statsColumn : PPtr[RectTransform]
	bumperPrompt : PPtr[GameObject]
@UTTCGen
class InventoryView(MonoBehaviour):
	characterColumn : PPtr[RectTransform]
	statsColumn : PPtr[RectTransform]
	bumperPrompt : PPtr[GameObject]
@UTTCGen
class JournalView(MonoBehaviour):
	pass
@UTTCGen
class LoadView(MonoBehaviour):
	pass
@UTTCGen
class LobbyManager(MonoBehaviour):
	newspaper : PPtr[Newspaper]
	debuggingFeatures : List[RectTransform]
@UTTCGen
class LobbyView(MonoBehaviour):
	initialSelected : PPtr[object] # XXX: Fallback of PPtr<Selectable>
@UTTCGen
class MainMenuView(MonoBehaviour):
	selectOverlayPrompt : PPtr[RectTransform]
	backOverlayPrompt : PPtr[RectTransform]
	labelBlock : PPtr[RectTransform]
	deLogo : PPtr[GameObject]
@UTTCGen
class OptionsScreen(MonoBehaviour):
	resetSettingsButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	isOnControllerView : bool
@UTTCGen
class OptionsView(MonoBehaviour):
	optionsScroll : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	firstSelectable : PPtr[object] # XXX: Fallback of PPtr<Selectable>
	alternativeSelectableFallback : PPtr[object] # XXX: Fallback of PPtr<Selectable>
	dropdownsToHide : List[object] # XXX: Fallback of TMP_Dropdown[]
	verticalStepScrollView : PPtr[VerticalStepScrollView]
	lastSelectedSelectable : PPtr[object] # XXX: Fallback of PPtr<Selectable>
@UTTCGen
class SAVE_LOAD_MODE(MonoBehaviour):
	value__ : int
@UTTCGen
class SaveGameListEntry(MonoBehaviour):
	normalState : SaveGameListEntryState
	hoveredState : SaveGameListEntryState
	nonEditableState : SaveGameListEntryState
	selectedState : SaveGameListEntryState
	pressedState : SaveGameListEntryState
	backgroundImage : PPtr[Image]
	saveNameInputField : PPtr[object] # XXX: Fallback of PPtr<InputField>
	loadButtonSelecteble : PPtr[object] # XXX: Fallback of PPtr<Selectable>
	saveDateText : PPtr[Text]
	saveHourText : PPtr[Text]
	newSaveText : PPtr[Text]
	saveNameInputFieldTMP : PPtr[object] # XXX: Fallback of PPtr<TMP_InputField>
	saveDateTextTMP : PPtr[object] # XXX: Fallback of PPtr<TMP_Text>
	saveHourTextTMP : PPtr[object] # XXX: Fallback of PPtr<TMP_Text>
	newSaveTextTMP : PPtr[object] # XXX: Fallback of PPtr<TMP_Text>
	useTMPro : bool
@UTTCGen
class SaveGameListEntryInputField(MonoBehaviour):
	saveGameListEntry : PPtr[SaveGameListEntry]
@UTTCGen
class SaveLoadController(MonoBehaviour):
	saveFileListContentPanel : PPtr[RectTransform]
	saveButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	saveGameFileListEntryPrefabLegacy : PPtr[SaveGameListEntry]
	sysSaveGameFileListEntryPrefabLegacy : PPtr[SaveGameListEntry]
	saveGameFileListEntryPrefabTMPro : PPtr[SaveGameListEntry]
	sysSaveGameFileListEntryPrefabTMPro : PPtr[SaveGameListEntry]
	fileListSeparator : PPtr[RectTransform]
	scrollArea : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	SelectedSaveGameFileButtonColor : ColorRGBA
	NormalSaveGameFileButtonColor : ColorRGBA
	titleLocalize : PPtr[object] # XXX: Fallback of PPtr<Localize>
	saveTerm : str
	overwriteTerm : str
	titleSaveTerm : str
	titleLoadTerm : str
	fileInfoComponentHolderPanel : PPtr[RectTransform]
	screenshotImagePanel : PPtr[Image]
	defaultSprite : PPtr[Sprite]
	errorLocalize : PPtr[object] # XXX: Fallback of PPtr<Localize>
	LoadButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	DeleteButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	verticalStep : PPtr[VerticalStepScrollView]
	buttonClickedSoundPlayer : PPtr[SoundPlayer]
@UTTCGen
class SaveLoadViewInitializer(MonoBehaviour):
	saveLoadScreenTemplate : PPtr[SaveLoadController]
@UTTCGen
class SaveView(MonoBehaviour):
	pass
@UTTCGen
class SpecialView(MonoBehaviour):
	pass
@UTTCGen
class StatsView(MonoBehaviour):
	equipButtonPrompt : PPtr[RectTransform]
	closeButtonPrompt : PPtr[RectTransform]
	localizedHelpfulText : PPtr[object] # XXX: Fallback of PPtr<Localize>
	thoughtCabinetTitle : PPtr[GameObject]
	inventoryTitle : PPtr[GameObject]
@UTTCGen
class ThoughtCabinetView(MonoBehaviour):
	statsColumn : PPtr[RectTransform]
	thoughtEquipment : PPtr[RectTransform]
	thoughtInventory : PPtr[RectTransform]
@UTTCGen
class ThoughtSplashScreenView(MonoBehaviour):
	tabController : PPtr[SplashScreenTabController]
	scrollRect : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	image : PPtr[Image]
	buttonClose : PPtr[object] # XXX: Fallback of PPtr<Button>
	titleText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	propertiesText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	completionDescriptionText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
@UTTCGen
class View(MonoBehaviour):
	pass
@UTTCGen
class VIEW_STACK_OPERATION(MonoBehaviour):
	value__ : int
@UTTCGen
class ViewController(MonoBehaviour):
	feldslide : PPtr[FeldSlide]
	cameraLockViews : List[int]
	current : int
@UTTCGen
class ViewDependentToggler(MonoBehaviour):
	activeOn : List[ViewType]
