# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.Gameplay.Charsheet

from .... import *
from ....DiscoPages.Elements.Charsheet import PageSystemStatPanel
from .... import SegmentIndicator
from .... import SkillLevelUpButton
from ....PagesSystem import SkillPortraitAnimatorHelperPageSystem
from .... import SkillPortraitOverviewPanel
from ....DiscoPages.Elements import SkillPortraitPanelPageSystem
from ....DiscoPages.Elements.Common import SwipeDetector
from .... import SwipeUIElementSelectionController
from .... import TabSwitchAnimationController
from .... import XPPanel

@UTTCGen
class CharsheetGameplayPage(MonoBehaviour):
	stats : List[PPtr[PageSystemStatPanel]]
	portraits : List[PPtr[SkillPortraitPanelPageSystem]]
	maximizeButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	minimizeButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	swipeDetectors : List[SwipeDetector]
@UTTCGen
class SkillOverviewGameplayPage(MonoBehaviour):
	skillInfoNavigateButtons : List[object] # XXX: Fallback of Button[]
	portraitSkillPipIndicator : PPtr[SegmentIndicator]
	skillPortraitAnimatorHelper : PPtr[SkillPortraitAnimatorHelperPageSystem]
	leftArrowButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	rightArrowButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	confirmButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	portraitOverviewPanel : PPtr[SkillPortraitOverviewPanel]
	leftPortraitOverviewPanel : PPtr[SkillPortraitOverviewPanel]
	rightPortraitOverviewPanel : PPtr[SkillPortraitOverviewPanel]
	tabSwitchAnimationController : PPtr[TabSwitchAnimationController]
	swipeAnimatorController : PPtr[SwipeUIElementSelectionController]
	extraText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	levelUpButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	skillLevelUpButton : PPtr[SkillLevelUpButton]
	xpPanel : PPtr[XPPanel]
