# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.Gameplay.Map

from .... import *
from .... import PageSystemJournalWhiteCheckUI

@UTTCGen
class MapPage(MonoBehaviour):
	skillcheckNavigateButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	mapSkillcheckPrefab : PPtr[object] # XXX: Fallback of PPtr<Button>
	mapRect : PPtr[RectTransform]
@UTTCGen
class MapSkillcheckDetailPage(MonoBehaviour):
	whiteCheckUI : PPtr[PageSystemJournalWhiteCheckUI]
@UTTCGen
class SelectedSkillcheckParameter(MonoBehaviour):
	pass
@UTTCGen
class SkillcheckListPage(MonoBehaviour):
	checksListContent : PPtr[Transform]
	whiteCheckItemPrefab : PPtr[PageSystemJournalWhiteCheckUI]
