# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for PagesSystem

from .. import *
from .. import MaterialValueUpdater

@UTTCGen
class SkillPortraitAnimatorHelperPageSystem(MonoBehaviour):
	portrait : PPtr[Image]
	portraitEffect : PPtr[Image]
	flickerRandomization : float
	materialValueUpdater : PPtr[MaterialValueUpdater]
