# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for PixelCrushers.DialogueSystem.SequencerCommands

from .... import *

@UTTCGen
class SequencerCommandAddFakeMoney(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandAddGraphito(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandAmbientVolume(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandAudioLoopPlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandAudioLoopStop(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandAudioPlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandBanishHUD(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandBanishInterface(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandBoomboxPlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandCameraRelock(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandCameraUnlock(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandCutsceneEnd(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandCutsceneStart(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandCutsceneState(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandCutsceneZoom(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandDesperationOverlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandDontChangeMusicUntilEndOfCutscene(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandEnable(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandEndGame(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandEndgameBoat(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandEndgameBoatDone(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandFadeToBlack(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandFadeToImage(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandFocusCamera(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandFocusCamera2(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandFocusCameraZoom(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandHideActualHeld(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandHideFow(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandHideOverlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandHidePortrait(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandHold(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandHoldText(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandIgnoreEnvironmentalMusic(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandInteract(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandLag(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandLuaRun(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandMoveCamera(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandMoveCharacter(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandMusicDecay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandMusicPlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandMusicPriorityReset(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandMusicVolume(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandPainOverlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandPlayAnimation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandPlayPartyMemberAnimation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandPlaySound(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandPosseEndgame(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandPostFX(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandRelease(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandReleaseText(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandRemoveWhiteCheck(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandResetCamera(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandResetTequilaLocation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandRotateCharacter(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSemiBlack(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSetBooleanAnimation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSetDestination(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSetFloatAnimation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSetFovVisible(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSetTriggerAnimation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandShowActualHeld(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSilence(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSleepingDockworkerPlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSpecialAnimation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandStartTime(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandStopConversation(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandStopTime(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandStopVoiceover(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandSwitchMaterials(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandToggleHeldAnimationLayer(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandTotalBlack(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandTravelTo(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandTriggerWeather(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandVoiceoverPlay(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandWaitFor(MonoBehaviour):
	isPlaying : bool
@UTTCGen
class SequencerCommandWaitForSeconds(MonoBehaviour):
	isPlaying : bool
