# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Dialogue

from ... import *

@UTTCGen
class Announcements(MonoBehaviour):
	pass
@UTTCGen
class AreaSpecificLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class CharacterLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class ClothingLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class CunoLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class DaytimeLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class DialogueLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class EnddayLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class EndgameLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class FELDLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class GenericLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class GraphicsLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class InventoryLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class KarmaLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class KimLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class LuaFunctionRegistry(MonoBehaviour):
	pass
@UTTCGen
class MapLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class MoneyLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class NLuaChecker(MonoBehaviour):
	pass
@UTTCGen
class OrbitLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class SoundLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class TaskLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class THCLuaFunctions(MonoBehaviour):
	pass
@UTTCGen
class WhirlingLuaFunctions(MonoBehaviour):
	pass
