# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Rebind

from .. import *

@UTTCGen
class RebindActionRecord(MonoBehaviour):
	actionLabel : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	bindingsContainer : PPtr[Transform]
	addBind : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class RebindBindingRecord(MonoBehaviour):
	bindingName : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	deviceClass : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	bindingSourceType : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	removeBind : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class RebindingUI(MonoBehaviour):
	mainWindow : PPtr[GameObject]
	actionPrefab : PPtr[RebindActionRecord]
	bindingPrefab : PPtr[RebindBindingRecord]
	actionsContainer : PPtr[Transform]
	refreshButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	disableListenButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	resetToDefault : PPtr[object] # XXX: Fallback of PPtr<Button>
	canvasGroup : PPtr[CanvasGroup]
