# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.Gameplay.Inventory

from .... import *
from ....DiscoPages.Elements.Inventory import InventoryEquipmentSlot
from ....Sunshine import InventoryTooltip
from ....DiscoPages.Elements.Inventory import PageSystemInventoryTabPanel
from ....DiscoPages.Elements.Common import SwipeDetector

@UTTCGen
class InventoryItemsNavigationParameters(MonoBehaviour):
	pass
@UTTCGen
class InventoryItemsPage(MonoBehaviour):
	statsOverlayButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	tabPanel : PPtr[PageSystemInventoryTabPanel]
	tooltip : PPtr[InventoryTooltip]
@UTTCGen
class InventoryManagerPageSystem(MonoBehaviour):
	equippableItemTypes : List[int]
@UTTCGen
class InventoryNavigationParameters(MonoBehaviour):
	pass
@UTTCGen
class InventoryPage(MonoBehaviour):
	statsOverlayButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	inventoryItemsNavigateButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	equipmentSlots : List[InventoryEquipmentSlot]
	swipeDetector : PPtr[SwipeDetector]
