# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Smaa

from .. import *

@UTTCGen
class DebugPass(MonoBehaviour):
	value__ : int
@UTTCGen
class EdgeDetectionMethod(MonoBehaviour):
	value__ : int
@UTTCGen
class MinAttribute(MonoBehaviour):
	pass
@UTTCGen
class PredicationPreset(MonoBehaviour):
	Threshold : float
	Scale : float
	Strength : float
@UTTCGen
class Preset(MonoBehaviour):
	DiagDetection : bool
	CornerDetection : bool
	Threshold : float
	DepthThreshold : float
	MaxSearchSteps : int
	MaxSearchStepsDiag : int
	CornerRounding : int
	LocalContrastAdaptationFactor : float
@UTTCGen
class QualityPreset(MonoBehaviour):
	value__ : int
@UTTCGen
class SMAA(MonoBehaviour):
	DebugPass : int
	Quality : int
	DetectionMethod : int
	UsePredication : bool
	CustomPreset : Preset
	CustomPredicationPreset : PredicationPreset
	Shader : PPtr[Shader]
	AreaTex : PPtr[Texture2D]
	SearchTex : PPtr[Texture2D]
