# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for PixelCrushers.DialogueSystem

from ... import *
from ... import Condition

@UTTCGen
class FOBarkOnIdle(MonoBehaviour):
	once : bool
	conversation : str
	condition : Condition
	skipIfNoValidEntries : bool
	exclusive : bool
	conversant : PPtr[Transform]
	useConversationTitlePicker : bool
	selectedDatabase : PPtr[object] # XXX: Fallback of PPtr<DialogueDatabase>
	barkOrder : int
	allowDuringConversations : bool
	cacheBarkLines : bool
	minSeconds : float
	maxSeconds : float
	target : PPtr[Transform]
@UTTCGen
class FOBarkOnLuaVariableChanged(MonoBehaviour):
	once : bool
	conversation : str
	condition : Condition
	skipIfNoValidEntries : bool
	exclusive : bool
	conversant : PPtr[Transform]
	useConversationTitlePicker : bool
	selectedDatabase : PPtr[object] # XXX: Fallback of PPtr<DialogueDatabase>
	barkOrder : int
	allowDuringConversations : bool
	cacheBarkLines : bool
	minSeconds : float
	maxSeconds : float
	target : PPtr[Transform]
