# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.OnSwipeDetected

from .... import *
from ....DiscoPages.Elements.Common import SwipeDetector

@UTTCGen
class ChangeGraphicColorOnSwipeDetected(MonoBehaviour):
	localSwipeDetector : PPtr[SwipeDetector]
	Active : bool
	targetUIElement : PPtr[object] # XXX: Fallback of PPtr<Graphic>
	targetColor : ColorRGBA
	distanceValueToFullColor : float
	alwaysChangeColorIfIsDrag : bool
	swipeDirectionToActivate : int
@UTTCGen
class EventOnSwipeDetected(MonoBehaviour):
	localSwipeDetector : PPtr[SwipeDetector]
	Active : bool
	activateOnDragEnd : bool
	distanceValueToActivate : float
	OnUpSwipe : object # XXX: Fallback of UnityEvent
	OnDownSwipe : object # XXX: Fallback of UnityEvent
	OnLeftSwipe : object # XXX: Fallback of UnityEvent
	OnRightSwipe : object # XXX: Fallback of UnityEvent
@UTTCGen
class MoveUIElementOnSwipeDetected(MonoBehaviour):
	localSwipeDetector : PPtr[SwipeDetector]
	Active : bool
	targetUIElement : PPtr[RectTransform]
	reachTargetSpeed : float
	minMaxX : Vector2f
	minMaxY : Vector2f
@UTTCGen
class OnSwipeDetected(MonoBehaviour):
	localSwipeDetector : PPtr[SwipeDetector]
	Active : bool
