# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for CollageMode.Scripts.Localization

from .... import *

@UTTCGen
class CollageLocalization(MonoBehaviour):
	pass
