# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.MainMenu

from ... import *
from ...DiscoPages.Elements.MainMenu import ArchetypeSelectMenuButton
from ...DiscoPages.Elements.MainMenu import ArchetypeSelectionIndicator
from ...DiscoPages.Elements.OnSwipeDetected import EventOnSwipeDetected
from ...DiscoPages.Elements.MainMenu import PageSystemMenuButton
from ... import SunshineCharacterTemplate

@UTTCGen
class CityViewLandingPage(MonoBehaviour):
	hiddenForwardButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	buttonGroups : PPtr[GameObject]
@UTTCGen
class InitialIntroPage(MonoBehaviour):
	transmissionToNextPage : float
	hiddenForwardButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	zaumLogo : PPtr[Image]
@UTTCGen
class MainMenuExpandedPage(MonoBehaviour):
	menuItemTemplate : PPtr[PageSystemMenuButton]
	buttonParent : PPtr[Transform]
@UTTCGen
class MainMenuPage(MonoBehaviour):
	buttonGroups : PPtr[GameObject]
	continueGame : PPtr[object] # XXX: Fallback of PPtr<Button>
	seeMoreSettings : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class NewspaperPage(MonoBehaviour):
	title : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	titleLocalize : PPtr[object] # XXX: Fallback of PPtr<Localize>
	opener : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	openerLocalize : PPtr[object] # XXX: Fallback of PPtr<Localize>
	pageNr : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	forward : PPtr[object] # XXX: Fallback of PPtr<Button>
	back : PPtr[object] # XXX: Fallback of PPtr<Button>
	closeNewspaperButton : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class SelectArchetypePage(MonoBehaviour):
	buttonTemplate : PPtr[ArchetypeSelectMenuButton]
	customCharacter : PPtr[ArchetypeSelectMenuButton]
	buttonsParent : PPtr[Transform]
	selectionScrollView : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	showNextTemplate : PPtr[object] # XXX: Fallback of PPtr<Button>
	showPreviousTemplate : PPtr[object] # XXX: Fallback of PPtr<Button>
	selectionIndicator : PPtr[ArchetypeSelectionIndicator]
	flash : PPtr[Image]
	portraits : List[Sprite]
	archetypes : List[SunshineCharacterTemplate]
	swipeDetector : PPtr[EventOnSwipeDetected]
@UTTCGen
class ToSPage(MonoBehaviour):
	acceptToS : PPtr[object] # XXX: Fallback of PPtr<Button>
