# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for AddressablesTools

from .. import *

@UTTCGen
class AssetBundleLoadAssetOperation(MonoBehaviour):
	pass
@UTTCGen
class AssetBundleLoadAssetOperationFull(MonoBehaviour):
	pass
@UTTCGen
class AssetBundleLoadAssetOperationSimulation(MonoBehaviour):
	pass
@UTTCGen
class AssetBundleLoadLevelOperation(MonoBehaviour):
	pass
@UTTCGen
class AssetBundleLoadManifestOperation(MonoBehaviour):
	pass
@UTTCGen
class AssetBundleLoadOperation(MonoBehaviour):
	pass
@UTTCGen
class AssetBundleManager(MonoBehaviour):
	pass
@UTTCGen
class LoadedAssetBundle(MonoBehaviour):
	m_AssetBundle : PPtr[AssetBundle]
	m_ReferencedCount : int
@UTTCGen
class Utility(MonoBehaviour):
	pass
