# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Conditions

from .. import *
from ..CollageMode import UnlockHiddenImage

@UTTCGen
class FilterChecker(MonoBehaviour):
	requiredFilter : int
@UTTCGen
class UnlockChecker(MonoBehaviour):
	unlockHiddenImage : PPtr[UnlockHiddenImage]
