# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements

from ... import *
from ... import SegmentIndicator
from ...Charsheet import SkillPortrayLabel
from ...DiscoPages.Elements.Common import SwipeDetector

@UTTCGen
class InventoryTabsDragController(MonoBehaviour):
	swipeDetector : PPtr[SwipeDetector]
@UTTCGen
class SkillPortraitPanelPageSystem(MonoBehaviour):
	portrait : PPtr[Image]
	frame : PPtr[Image]
	isHovered : bool
	isSelectHovered : bool
	isUpgradeable : bool
	signatureFrame : PPtr[Image]
	skillPips : PPtr[SegmentIndicator]
	levelUpButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	selectButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	skillPortrayLabel : PPtr[SkillPortrayLabel]
	mode : int
	skill : int
