# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Journal.Controller

from .... import *
from ....Sunshine.Journal import JournalSubtasksController
from ....Sunshine.Journal import JournalTaskUI
from .... import JournalWhiteCheckUI
from .... import LayoutDisabler
from .... import TweenRectTransform
from .... import VerticalStepScrollView
from .... import WhiteCheckCoordinatesUI

@UTTCGen
class JournalTasksController(MonoBehaviour):
	taskTemplate : PPtr[JournalTaskUI]
	taskListContainer : PPtr[RectTransform]
	tasksVerticalStep : PPtr[VerticalStepScrollView]
	layoutDisabler : PPtr[LayoutDisabler]
@UTTCGen
class JournalController(MonoBehaviour):
	tasklist : PPtr[JournalTasksController]
	tasksTab : PPtr[GameObject]
	tasksLabel : PPtr[RectTransform]
	tasksToggle : PPtr[object] # XXX: Fallback of PPtr<Toggle>
	subtasksController : PPtr[JournalSubtasksController]
	taskDescriptionArea : PPtr[RectTransform]
	selectedTaskTitle : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	selectedTaskFiledDateTime : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	taskDescriptionTextField : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	taskStateDescription : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	showActiveToggle : PPtr[object] # XXX: Fallback of PPtr<Toggle>
	showDoneToggle : PPtr[object] # XXX: Fallback of PPtr<Toggle>
	showActiveLabel : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	showDoneLabel : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	tasksTogglesBackground : PPtr[TweenRectTransform]
	profileMissing : PPtr[GameObject]
	profileDiscovered : PPtr[GameObject]
	checksTab : PPtr[GameObject]
	map : PPtr[GameObject]
	mapMissing : PPtr[GameObject]
	checkTemplate : PPtr[JournalWhiteCheckUI]
	checkCoords : PPtr[WhiteCheckCoordinatesUI]
	checksListContainer : PPtr[RectTransform]
	checksLabel : PPtr[RectTransform]
	checksToggle : PPtr[object] # XXX: Fallback of PPtr<Toggle>
	checksTogglesBackground : PPtr[TweenRectTransform]
	checksVerticalStep : PPtr[VerticalStepScrollView]
	checksRightSelectable : PPtr[object] # XXX: Fallback of PPtr<Selectable>
	TasksNotifyIcon : PPtr[GameObject]
	MapNotifyIcon : PPtr[GameObject]
	ActiveTasksNotifyIcon : PPtr[GameObject]
	DoneTasksNotifyIcon : PPtr[GameObject]
	shownWhiteChecksList : List[PPtr[JournalWhiteCheckUI]]
@UTTCGen
class JournalWeekdaysController(MonoBehaviour):
	weekDayTextPrefab : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
