# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.Inventory

from .... import *
from .... import TweenRectTransform

@UTTCGen
class InventoryEquipmentSlot(MonoBehaviour):
	slotType : int
	fillImage : PPtr[Image]
	itemImage : PPtr[Image]
	slotTypeText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
@UTTCGen
class InventoryItemSlot(MonoBehaviour):
	itemImage : PPtr[Image]
	backgroundImage : PPtr[Image]
@UTTCGen
class PageSystemInventoryGrids(MonoBehaviour):
	inventoryGridPrefab : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	cellPrefab : PPtr[InventoryItemSlot]
	gridsScrollView : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	gridsParent : PPtr[Transform]
@UTTCGen
class PageSystemInventoryTabButton(MonoBehaviour):
	button : PPtr[object] # XXX: Fallback of PPtr<Button>
	text : PPtr[object] # XXX: Fallback of PPtr<TMP_Text>
	enabledTabTextColor : ColorRGBA
	disabledTabTextColor : ColorRGBA
	buttonType : int
@UTTCGen
class PageSystemInventoryTabPanel(MonoBehaviour):
	inventoryGrids : PPtr[PageSystemInventoryGrids]
	tabs : List[PPtr[PageSystemInventoryTabButton]]
	nextTabButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	previousTabButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	selectedTabBackground : PPtr[TweenRectTransform]
