# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.Charsheet

from .... import *
from .... import AbilityGradeFlipClock
from .... import PipVisualizer
from ....DiscoPages.Elements.Common import SwipeDetector

@UTTCGen
class PageSystemStatPanel(MonoBehaviour):
	m_Navigation : object # XXX: Fallback of Navigation
	m_Transition : int
	m_Colors : object # XXX: Fallback of ColorBlock
	m_SpriteState : object # XXX: Fallback of SpriteState
	m_AnimationTriggers : object # XXX: Fallback of AnimationTriggers
	m_Interactable : bool
	m_TargetGraphic : PPtr[object] # XXX: Fallback of PPtr<Graphic>
	tmpSkillOverviewPageButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	minimal : PPtr[RectTransform]
	maximal : PPtr[RectTransform]
	statPips : PPtr[PipVisualizer]
	statPipsMin : PPtr[PipVisualizer]
	statName : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	statNameMin : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	statNumber : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	selectionMarker : PPtr[Image]
	abilityGradeFlipClock : PPtr[AbilityGradeFlipClock]
	ability : int
@UTTCGen
class StatLevelerPageSystem(MonoBehaviour):
	levelUp : PPtr[object] # XXX: Fallback of PPtr<Button>
	levelDown : PPtr[object] # XXX: Fallback of PPtr<Button>
	backgroundImg : PPtr[Image]
	swipeDetector : PPtr[SwipeDetector]
