# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.Gameplay.THC

from .... import *
from ....DiscoPages.Elements.Common import InPageMessage
from ....DiscoPages.Elements.THC import PageSystemThoughtOceanSlot
from .... import SwipeUIElementSelectionController
from .... import TabSwitchAnimationController
from ....Sunshine import ThoughtSlot
from .... import XPPanel

@UTTCGen
class THCDetailsPage(MonoBehaviour):
	scrollRect : PPtr[object] # XXX: Fallback of PPtr<ScrollRect>
	graphic : PPtr[Image]
	nextGraphic : PPtr[Image]
	previousGraphic : PPtr[Image]
	thoughtResearchFillAmount : PPtr[Image]
	title : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	subtitle : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	researchBonus : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	description : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	actionButtonLabel : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	actionButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	xpPanel : PPtr[XPPanel]
	selectNextThoughtButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	selectPreviousThoughtButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	tabSwitchAnimationController : PPtr[TabSwitchAnimationController]
	swipeUiController : PPtr[SwipeUIElementSelectionController]
	toggleProblemSolutionButtons : List[object] # XXX: Fallback of Button[]
@UTTCGen
class THCListPage(MonoBehaviour):
	thoughtButtonPrefab : PPtr[PageSystemThoughtOceanSlot]
	columns : List[RectTransform]
	thoughtNotUnlockedMessage : PPtr[InPageMessage]
	sortButton : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class THCPage(MonoBehaviour):
	slotPrefab : PPtr[ThoughtSlot]
	columns : List[RectTransform]
	statsNavigateButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	thcNavigateButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	pressedButtonColor : ColorRGBA
@UTTCGen
class THCSplashscreenPage(MonoBehaviour):
	thoughtTitleText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	conclusionText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	propertiesText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	thoughtImage : PPtr[Image]
	closeButton : PPtr[object] # XXX: Fallback of PPtr<Button>
