# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Journal

from ... import *
from ... import SunshineClockTime
from ...LocalizationCustomSystem import TranslationString

@UTTCGen
class Completeable(MonoBehaviour):
	LocalizedNameTerm : TranslationString
	LocalizedDescriptionTerm : TranslationString
@UTTCGen
class JournalModel(MonoBehaviour):
	OnClearGainedTasksAndResetStates : object # XXX: Fallback of UnityEvent
@UTTCGen
class JournalSubtask(MonoBehaviour):
	LocalizedNameTerm : TranslationString
	LocalizedDescriptionTerm : TranslationString
@UTTCGen
class JournalSubtaskUI(MonoBehaviour):
	aquisitionTime : SunshineClockTime
	taskNameTextField : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	undoneColor : ColorRGBA
	doneColor : ColorRGBA
	hiddenColor : ColorRGBA
@UTTCGen
class JournalSubtasksController(MonoBehaviour):
	subtaskTemplate : PPtr[JournalSubtaskUI]
	subtaskListContainer : PPtr[RectTransform]
	subtasksPanel : PPtr[RectTransform]
@UTTCGen
class JournalTask(MonoBehaviour):
	LocalizedNameTerm : TranslationString
	LocalizedDescriptionTerm : TranslationString
	reward : int
@UTTCGen
class JournalTaskUI(MonoBehaviour):
	m_Navigation : object # XXX: Fallback of Navigation
	m_Transition : int
	m_Colors : object # XXX: Fallback of ColorBlock
	m_SpriteState : object # XXX: Fallback of SpriteState
	m_AnimationTriggers : object # XXX: Fallback of AnimationTriggers
	m_Interactable : bool
	m_TargetGraphic : PPtr[object] # XXX: Fallback of PPtr<Graphic>
	aquisitionTime : SunshineClockTime
	taskNameTextField : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	undoneColor : ColorRGBA
	doneColor : ColorRGBA
	highlightedColor : ColorRGBA
	hiddenColor : ColorRGBA
	selectionBackground : PPtr[Image]
	timedTaskNotifier : PPtr[Image]
	freshDot : PPtr[Image]
	Indent : int
	AlwaysIndentForTimedTaskImage : bool
@UTTCGen
class JournalWatchman(MonoBehaviour):
	pass
@UTTCGen
class Quicktravel(MonoBehaviour):
	pass
@UTTCGen
class QuicktravelButton(MonoBehaviour):
	m_Navigation : object # XXX: Fallback of Navigation
	m_Transition : int
	m_Colors : object # XXX: Fallback of ColorBlock
	m_SpriteState : object # XXX: Fallback of SpriteState
	m_AnimationTriggers : object # XXX: Fallback of AnimationTriggers
	m_Interactable : bool
	m_TargetGraphic : PPtr[object] # XXX: Fallback of PPtr<Graphic>
	locationMarker : str
	activationDistance : float
	travelHereLabel : PPtr[CanvasGroup]
	youAreHereLabel : PPtr[CanvasGroup]
	image : PPtr[Image]
	actionButton : PPtr[Image]
	wasVisited : bool
@UTTCGen
class QuicktravelController(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	churchButton : PPtr[QuicktravelButton]
	fishingVillageButton : PPtr[QuicktravelButton]
	martinaiseButton : PPtr[QuicktravelButton]
	wasQuicktravelChurchDiscovered : bool
	wasQuicktravelFishingVillageDiscovered : bool
@UTTCGen
class QuicktravelMarker(MonoBehaviour):
	wasVisited : bool
	locationMarkerTag : str
	activationRadius : float
