# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.Common

from .... import *

@UTTCGen
class BackButtonsLayout(MonoBehaviour):
	backButtons : List[object] # XXX: Fallback of Button[]
@UTTCGen
class InPageMessage(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	contentMessage : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	showHideDuration : float
	duration : float
@UTTCGen
class RotatedFitter(MonoBehaviour):
	pass
@UTTCGen
class SwipeDetector(MonoBehaviour):
	useGlobalEvent : bool
	stopDetectingSwipesAfterFirstOne : bool
	releaseToSwipe : bool
	minSwipeDistance : float
@UTTCGen
class SwipeDetectorExtension(MonoBehaviour):
	pass
