# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Accessibility

from .. import *
from .. import AudioCaptionsElement

@UTTCGen
class AccessibilityManager(MonoBehaviour):
	pass
@UTTCGen
class AudioCaptionsManager(MonoBehaviour):
	audioCaptionsPrefab : PPtr[AudioCaptionsElement]
	captionsParent : PPtr[RectTransform]
@UTTCGen
class InputDelayController(MonoBehaviour):
	pass
