# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for VOTool

from .. import *

@UTTCGen
class AlternativeVoiceClipInformation(MonoBehaviour):
	AlternativeID : int
	AlternativeAssetName : str
	AlternativeClipPath : str
	DoesNotNeedVO : bool
@UTTCGen
class DialogueEntryExtension(MonoBehaviour):
	pass
@UTTCGen
class VoiceClipInformation(MonoBehaviour):
	AssetName : str
	ArticyID : str
	AssetBundle : str
	PathToClipInProject : str
	DoesNotNeedVO : bool
	alternativeVoiceClips : List[AlternativeVoiceClipInformation]
@UTTCGen
class VOClipsListToDictonaryThreadJob(MonoBehaviour):
	sourceClipInformations : List[VoiceClipInformation]
@UTTCGen
class VoiceOverClipsLibrary(MonoBehaviour):
	clipInformations : List[VoiceClipInformation]
@UTTCGen
class VoiceOverClipsPlayer(MonoBehaviour):
	voiceOverClipsLibrary : PPtr[VoiceOverClipsLibrary]
@UTTCGen
class VoiceOverPlayer(MonoBehaviour):
	pass
@UTTCGen
class VoiceOverSystem(MonoBehaviour):
	pass
