# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Radial

from .. import *

@UTTCGen
class RadialMenu(MonoBehaviour):
	CharSheet : PPtr[Image]
	CharSheetTape : PPtr[Image]
	CharSheetButton : PPtr[Image]
	CharSheetOpen : PPtr[Sprite]
	CharSheetClosed : PPtr[Sprite]
	Inventory : PPtr[Image]
	InventoryTape : PPtr[Image]
	InventoryButton : PPtr[Image]
	InventoryOpen : PPtr[Sprite]
	InventoryClosed : PPtr[Sprite]
	Thc : PPtr[Image]
	ThcTape : PPtr[Image]
	ThcButton : PPtr[Image]
	ThcOpen : PPtr[Sprite]
	ThcClosed : PPtr[Sprite]
	Journal : PPtr[Image]
	JournalTape : PPtr[Image]
	JournalButton : PPtr[Image]
	JournalOpen : PPtr[Sprite]
	JournalClosed : PPtr[Sprite]
	Arrow : PPtr[Image]
	TapeHighlighted : PPtr[Sprite]
	TapeNormal : PPtr[Sprite]
	currentSelection : int
@UTTCGen
class Selection(MonoBehaviour):
	value__ : int
@UTTCGen
class SelectionExtension(MonoBehaviour):
	pass
