# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for FontSizeProfiles.UIChangers

from ... import *
from ... import Text

@UTTCGen
class TextFontSizeChanger(MonoBehaviour):
	textElementID : str
	textElement : PPtr[Text]
@UTTCGen
class TMPChanger(MonoBehaviour):
	textElementID : str
@UTTCGen
class TMPFontAutoSizeChanger(MonoBehaviour):
	textElementID : str
	textElement : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
@UTTCGen
class TMPFontSizeChanger(MonoBehaviour):
	textElementID : str
	textElement : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
@UTTCGen
class TMPHeightChanger(MonoBehaviour):
	textElementID : str
	rectElement : PPtr[RectTransform]
@UTTCGen
class TMPMonoBehaviourSetEnableChanger(MonoBehaviour):
	textElementID : str
	component : PPtr[MonoBehaviour]
@UTTCGen
class TMPRectChanger(MonoBehaviour):
	textElementID : str
	rectElement : PPtr[RectTransform]
@UTTCGen
class TMPRectHorizontalChanger(MonoBehaviour):
	textElementID : str
	rectElement : PPtr[RectTransform]
