# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for TwitchIntegration

from .. import *
from ..Sunshine.Metric import CharacterBuff
from ..Sunshine.Metric import CharacterEffect
from .. import Text

@UTTCGen
class TwitchGameDataUpdater(MonoBehaviour):
	pass
@UTTCGen
class TwitchMeditation(MonoBehaviour):
	pass
@UTTCGen
class TwitchMeditationUI(MonoBehaviour):
	meditationStart : PPtr[object] # XXX: Fallback of PPtr<Button>
	timer : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	meditationInProgress : PPtr[Image]
	canvasGroup : PPtr[CanvasGroup]
	buff : PPtr[CharacterBuff]
	buffEffect : PPtr[CharacterEffect]
	debuff : PPtr[CharacterBuff]
	debuffEffect : PPtr[CharacterEffect]
@UTTCGen
class TwitchSettingsUI(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	secretKeyField : PPtr[object] # XXX: Fallback of PPtr<InputField>
	connectionStatus : PPtr[Text]
	connectToTwitch : PPtr[object] # XXX: Fallback of PPtr<Button>
	disconnectFromTwitch : PPtr[object] # XXX: Fallback of PPtr<Button>
