# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for NotificationSystem

from .. import *
from .. import DiceRollsScriptableObject
from ..LocalizationCustomSystem import TranslationString

@UTTCGen
class HideSide(MonoBehaviour):
	value__ : int
@UTTCGen
class Notification(MonoBehaviour):
	Breaked : bool
@UTTCGen
class NotificationFinishedTask(MonoBehaviour):
	Breaked : bool
@UTTCGen
class NotificationLocalized(MonoBehaviour):
	Breaked : bool
@UTTCGen
class NotificationPanel(MonoBehaviour):
	_iconImage : PPtr[Image]
	_blurIconImage : PPtr[Image]
	_leftSecondaryIconImage : PPtr[Image]
	_leftSecondaryIconBlurImage : PPtr[Image]
	_rightSecondaryIconImage : PPtr[Image]
	_rightSecondaryIconBlurImage : PPtr[Image]
	_headerText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	_headerTextShadow : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	_headerLabel : PPtr[Image]
	_descriptionText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	_descriptionTextShadow : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	_descriptionLabel : PPtr[Image]
	_backgroundEffectImage : PPtr[Image]
	_labelsMaterial : PPtr[Material]
	_textsMaterialTerm : TranslationString
	_flashEffectMaterial : PPtr[Material]
	_slidingContentRect : PPtr[RectTransform]
@UTTCGen
class NotificationScriptableObject(MonoBehaviour):
	NotificationType : int
	DefaultHeader : str
	LocalizedDefaultHeaderTerm : TranslationString
	localizedHeaderSuffix : str
	MainSprite : PPtr[Sprite]
	BlurSprite : PPtr[Sprite]
	LeftSecondarySprite : PPtr[Sprite]
	LeftSecondaryBlurSprite : PPtr[Sprite]
	RightSecondarySprite : PPtr[Sprite]
	RightSecondaryBlurSprite : PPtr[Sprite]
	NeonColor : ColorRGBA
	LabelColor : ColorRGBA
	ScreenFlash : ColorRGBA
	HideSide : int
	ShowingTime : float
	StayTime : float
	HidingTime : float
	SlideDist : float
	audioClipGroup : str
	audioClipId : str
	WaitingForAction : bool
	cameraFX : str
	cameraFXArray : List[str]
@UTTCGen
class NotificationManager(MonoBehaviour):
	_notificationSettingsList : List[PPtr[NotificationScriptableObject]]
	_diceRollsData : PPtr[DiceRollsScriptableObject]
	_notificationPanel : PPtr[NotificationPanel]
@UTTCGen
class NotificationMoney(MonoBehaviour):
	Breaked : bool
@UTTCGen
class NotificationTester(MonoBehaviour):
	pass
@UTTCGen
class NotificationType(MonoBehaviour):
	value__ : int
@UTTCGen
class NotificationUtil(MonoBehaviour):
	pass
@UTTCGen
class NotificationXP(MonoBehaviour):
	Breaked : bool
