# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.THC

from .... import *
from ....Sunshine.Metric import ThoughtCabinetProject
from ....Sunshine import ThoughtInteractButton
from ....Sunshine import ThoughtSlot
from .... import ThoughtSlotActionButton

@UTTCGen
class PageSystemThoughtOceanSlot(MonoBehaviour):
	HasButton : bool
	UnlockButton : PPtr[GameObject]
	interactButtonUnlock : PPtr[object] # XXX: Fallback of PPtr<Button>
	interactButtonThought : PPtr[ThoughtInteractButton]
	PlaceForUnlockButton : PPtr[Transform]
	_anim : PPtr[Animation]
	_actionButton : PPtr[ThoughtSlotActionButton]
	_slotImage : PPtr[Image]
	_doubleFrame : PPtr[Image]
	_thoughtProjectImage : PPtr[Image]
	_fillableArea : PPtr[Image]
	_fillableAreaBackground : PPtr[Image]
	_thoughtNameText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	_unlockSlotStarPip : PPtr[Image]
@UTTCGen
class PageSystemThoughtSlot(MonoBehaviour):
	m_Navigation : object # XXX: Fallback of Navigation
	m_Transition : int
	m_Colors : object # XXX: Fallback of ColorBlock
	m_SpriteState : object # XXX: Fallback of SpriteState
	m_AnimationTriggers : object # XXX: Fallback of AnimationTriggers
	m_Interactable : bool
	m_TargetGraphic : PPtr[object] # XXX: Fallback of PPtr<Graphic>
	HasButton : bool
	UnlockButton : PPtr[GameObject]
	interactButtonUnlock : PPtr[object] # XXX: Fallback of PPtr<Button>
	interactButtonThought : PPtr[ThoughtInteractButton]
	PlaceForUnlockButton : PPtr[Transform]
	_anim : PPtr[Animation]
	_actionButton : PPtr[ThoughtSlotActionButton]
	_slotImage : PPtr[Image]
	_doubleFrame : PPtr[Image]
	_thoughtProjectImage : PPtr[Image]
	_fillableArea : PPtr[Image]
	_fillableAreaBackground : PPtr[Image]
	_thoughtNameText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	_unlockSlotStarPip : PPtr[Image]
@UTTCGen
class PageSystemThoughtSlotHover(MonoBehaviour):
	_slotGlow : PPtr[Image]
@UTTCGen
class SelectedThoughtAndSlotParameter(MonoBehaviour):
	project : PPtr[ThoughtCabinetProject]
	thoughtoceanSlot : PPtr[PageSystemThoughtOceanSlot]
	selectedFreeThougthSlot : PPtr[ThoughtSlot]
@UTTCGen
class SelectedThoughtSlotParameter(MonoBehaviour):
	thoughtSlot : PPtr[ThoughtSlot]
@UTTCGen
class SortingOptions(MonoBehaviour):
	value__ : int
