# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.Common

from ... import *
from ...DiscoPages.Elements.MainMenu import PageSystemMenuButton

@UTTCGen
class BaseMenuPage(MonoBehaviour):
	menuItemTemplate : PPtr[PageSystemMenuButton]
	buttonParent : PPtr[Transform]
@UTTCGen
class LoadingPage(MonoBehaviour):
	pass
@UTTCGen
class MessagePage(MonoBehaviour):
	title : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	content : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	okButton : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class OptionsPage(MonoBehaviour):
	pass
@UTTCGen
class QuestionPage(MonoBehaviour):
	title : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	content : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	yesButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	noButton : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class TutorialOverlayPage(MonoBehaviour):
	pass
