# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for FontSizeProfiles.BuildParts

from ... import *
from ...FontSizeProfiles import AutoFontSizePerLanguage
from ...FontSizeProfiles import FontSizePerLanguage

@UTTCGen
class AutoTextElementSettings(MonoBehaviour):
	textElementID : str
	sizes : List[AutoFontSizePerLanguage]
@UTTCGen
class ElementSettings(MonoBehaviour):
	textElementID : str
@UTTCGen
class MonoBehaviourEnableSettings(MonoBehaviour):
	textElementID : str
	isEnabled : bool
@UTTCGen
class RectElementHeightSettings(MonoBehaviour):
	textElementID : str
	height : float
@UTTCGen
class RectElementHorizontalSettings(MonoBehaviour):
	textElementID : str
	anchoredPositionX : float
	sizeDeltaX : float
@UTTCGen
class RectElementSettings(MonoBehaviour):
	textElementID : str
	localPosition : Vector3f
	anchoredPosition : Vector2f
	sizeDelta : Vector2f
@UTTCGen
class TextElementSettings(MonoBehaviour):
	textElementID : str
	sizes : List[FontSizePerLanguage]
