# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Charsheet

from .. import *
from .. import OutsideColumnNavigationReferences
from .. import SkillPortraitPanel

@UTTCGen
class ISkillPortraitLabelHandler(MonoBehaviour):
	pass
@UTTCGen
class TranslationScriptable(MonoBehaviour):
	language : str
	scriptable : PPtr[object] # XXX: Fallback of PPtr<ScriptableObject>
@UTTCGen
class SkillPortraitLabelsConfigurator(MonoBehaviour):
	labelsSettings : List[TranslationScriptable]
@UTTCGen
class SkillPortraitLabelSettings(MonoBehaviour):
	skill : int
	labelText : str
	fontSize : float
	leftMargin : float
	lineSpace : float
	textOffset : Vector2f
	labelOffset : Vector2f
	nameplateSize : Vector2f
@UTTCGen
class SkillPortraitLabelsPreset(MonoBehaviour):
	labelsSettings : List[SkillPortraitLabelSettings]
@UTTCGen
class SkillPortrayConfigurator(MonoBehaviour):
	prefab : PPtr[SkillPortraitPanel]
	parent : PPtr[Transform]
	skillList : List[SkillPortraitPanel]
	navigationReferences : List[OutsideColumnNavigationReferences]
@UTTCGen
class SkillPortrayLabel(MonoBehaviour):
	nameplateRect : PPtr[RectTransform]
	nameplateBackground : PPtr[Image]
	skillName : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	skillNumber : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
@UTTCGen
class TranslationObject(MonoBehaviour):
	language : str
	prefabToSpawn : PPtr[GameObject]
@UTTCGen
class TranslatedObjectSpawner(MonoBehaviour):
	translationList : List[TranslationObject]
