# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for FortressOccident

from .. import *
from .. import Camera
from ..Sunshine import CameraMarker
from .. import ColorFiller
from ..Sunshine import FormationMarker
from .. import KimSwitchBoolean
from .. import LayerElement
from .. import MovementValidation
from .. import PostFX
from .. import SceneProperties
from .. import ScreenPointToRay
from ..Voidforge import TweenAlpha
from ..Sunshine import VitruvianManager

@UTTCGen
class AnimatedVariable(MonoBehaviour):
	amount : float
	overrideAnimation : bool
	modifiedByHeartbeat : bool
@UTTCGen
class ApplicationManager(MonoBehaviour):
	ScenePropertiesList : List[SceneProperties]
@UTTCGen
class BaseCustomCursor(MonoBehaviour):
	mode : int
@UTTCGen
class BasicEntity(MonoBehaviour):
	_interactionRadius : float
	outlinesOverride : bool
	conversation : str
	themesong : str
@UTTCGen
class CameraController(MonoBehaviour):
	screenPointToRay : PPtr[ScreenPointToRay]
	isSlaved : bool
	panSpeed : float
	panSpeedVector : Vector2f
	zoomFocusLimits : Vector2f
	viewportFocus : Vector2f
	zoomValue : float
	zoomLimitsExt : Vector2f
	zoomLimitsInt : Vector2f
	zoomSpeed : float
	zoomScrollWheelSpeed : float
	zoomScrollWheelSmoothing : bool
	jitterKiller : bool
	maxZoomScreenPosition : Vector2f
	minZoomScreenPosition : Vector2f
	currentViewportFocus : Vector2f
	isCameraFocusingOnInventory : bool
@UTTCGen
class CameraFocusData(MonoBehaviour):
	position : Vector3f
	zoom : float
	name : str
@UTTCGen
class CameraFocusPlacer(MonoBehaviour):
	cameraFocusDataList : List[CameraFocusData]
@UTTCGen
class Character(MonoBehaviour):
	_interactionRadius : float
	outlinesOverride : bool
	conversation : str
	themesong : str
	movementMode : int
	rootBone : PPtr[Transform]
	headBone : PPtr[Transform]
	rightHandBone : PPtr[Transform]
	leftHandBone : PPtr[Transform]
	movementValidator : PPtr[MovementValidation]
	navMeshObstacle : PPtr[NavMeshObstacle]
	movementCommandLock : bool
	enableMovementOnEnable : bool
	_rotationLock : int
	preventResetAtEndOfConversation : bool
	selectionMarker : PPtr[GameObject]
	_isSelected : bool
	_bodyRenderer : PPtr[SkinnedMeshRenderer]
	_vitruvian : PPtr[VitruvianManager]
	_isVitruvianSet : bool
	noShadow : bool
	isGhost : bool
	highlightStencilLayer : int
	inventoryCameraTarget : PPtr[Transform]
	offset : Vector3f
@UTTCGen
class CharacterAnimator(MonoBehaviour):
	animatorSpeedCutoff : float
	speedParameter : str
	angularSpeedParameter : str
@UTTCGen
class CharacterNavigator(MonoBehaviour):
	walkSpeed : float
	runSpeed : float
	autoRunDistance : float
@UTTCGen
class CursorType(MonoBehaviour):
	cursorSprite : PPtr[Texture2D]
	hotspot : Vector2f
@UTTCGen
class Curtains(MonoBehaviour):
	_interactionRadius : float
	outlinesOverride : bool
	conversation : str
	themesong : str
	openRotation : Vector3f
	closedRotation : Vector3f
	doorAnimSpeed : float
	openingSoundGroup : str
	openingSound : str
@UTTCGen
class CustomCursor(MonoBehaviour):
	mode : int
	cursor : PPtr[CursorType]
	alternateCursors : List[CursorType]
@UTTCGen
class DialogueImage(MonoBehaviour):
	imageLayerTemplate : PPtr[LayerElement]
	localizedImageLayerTemplate : PPtr[LayerElement]
	overlayHolder : PPtr[Transform]
	spriteMaterial : PPtr[Material]
	translationSpriteMaterial : PPtr[Material]
	flashMaterial : PPtr[Material]
	flashDuration : float
@UTTCGen
class Door(MonoBehaviour):
	_interactionRadius : float
	outlinesOverride : bool
	conversation : str
	themesong : str
	openRotation : Vector3f
	closedRotation : Vector3f
	doorAnimSpeed : float
@UTTCGen
class EntityStateChecker(MonoBehaviour):
	dialogueMode : object # XXX: Fallback of UnityEvent
	transportMode : object # XXX: Fallback of UnityEvent
	checkableBoolean : str
	checkableBoolean2 : str
@UTTCGen
class FeldBase(MonoBehaviour):
	speedMultiplier : float
	lengthMultiplier : float
	preDelay : float
	mainTape : bool
@UTTCGen
class FeldController(MonoBehaviour):
	feldCamera : PPtr[Camera]
	feldBlend : PPtr[GameObject]
	feldAnimatorController : PPtr[RuntimeAnimatorController]
	feldAnimatorControllerUltrawide : PPtr[RuntimeAnimatorController]
	feldRightPieces : List[FeldBase]
	feldContainerPieces : List[FeldBase]
	feldHUDPieces : List[FeldBase]
	feldTweenAlpha : PPtr[TweenAlpha]
	introBlend : PPtr[GameObject]
	introAnimatorController : PPtr[RuntimeAnimatorController]
	feldContainer : PPtr[GameObject]
	feldHUD : PPtr[GameObject]
	feldClock : PPtr[GameObject]
	rollLength : float
	flashDuration : float
	successFlashColor : ColorRGBA
	failFlashColor : ColorRGBA
	feldFlashes : bool
@UTTCGen
class FOComponent(MonoBehaviour):
	pass
@UTTCGen
class FOComponentExtensions(MonoBehaviour):
	pass
@UTTCGen
class FXSettings(MonoBehaviour):
	name : str
	colorOfFade : ColorRGBA
	colorOfPain : ColorRGBA
	isToggled : bool
	time : float
	fisheye : AnimatedVariable
	noise : AnimatedVariable
	fade : AnimatedVariable
	pain : AnimatedVariable
	heartbeats : AnimatedVariable
	mask : PPtr[Texture2D]
	callEvent : object # XXX: Fallback of UnityEvent
	fadeIsAdditive : bool
	isActive : bool
@UTTCGen
class FX(MonoBehaviour):
	obj : PPtr[SpriteRenderer]
	settings : List[FXSettings]
	settingsTimeFreeze : FXSettings
	heartbeatSpeed : float
	overrideEval : float
	evalDebug : float
	currentlyPlaying : int
	post : PPtr[PostFX]
	vignetteMaterial : PPtr[Material]
	vignetteTexture : PPtr[Texture2D]
	vignetteDarkTexture : PPtr[Texture2D]
	timeFreezeActive : bool
@UTTCGen
class GameEntity(MonoBehaviour):
	_interactionRadius : float
@UTTCGen
class GameEntityEvent(MonoBehaviour):
	onActivate : object # XXX: Fallback of UnityEvent
	onDeactivate : object # XXX: Fallback of UnityEvent
@UTTCGen
class Interactable(MonoBehaviour):
	pass
@UTTCGen
class InteractableWithDialogueCursor(MonoBehaviour):
	mode : int
	InteractableCursor : PPtr[CursorType]
	DialogueCursor : PPtr[CursorType]
@UTTCGen
class ManualSoundRemote(MonoBehaviour):
	_controllerIndex : int
	_playlistIndex : int
	_clipIndex : int
	Controller : str
	Playlist : str
	Clip : str
	Group : str
	_functionIndex : int
	activateOnStart : bool
	Volume : float
	Fade : float
	Spatial : float
	played : bool
	typeID : int
	settingID : int
@UTTCGen
class MouseOverHighlight(MonoBehaviour):
	isOutlined : bool
	lastMouseover : bool
	highlightState : bool
@UTTCGen
class NavMeshClickHandler(MonoBehaviour):
	pass
@UTTCGen
class OutlineIndex(MonoBehaviour):
	value__ : int
@UTTCGen
class Party(MonoBehaviour):
	isPlayerParty : bool
	lastCameraMarker : PPtr[CameraMarker]
	lastFormationMarker : PPtr[FormationMarker]
@UTTCGen
class PersistentObject(MonoBehaviour):
	pass
@UTTCGen
class RemovingTransitionEntity(MonoBehaviour):
	_interactionRadius : float
	outlinesOverride : bool
	conversation : str
	themesong : str
	area : str
	destination : str
	IsLocked : bool
	kimSwitches : List[KimSwitchBoolean]
	removeKimAndWaitHere : int
@UTTCGen
class SceneTransitionManager(MonoBehaviour):
	colorFiller : PPtr[ColorFiller]
	loadingScreen : PPtr[TweenAlpha]
	loadingPanelImage : PPtr[Image]
@UTTCGen
class ScrollWheelZoomAttenuator(MonoBehaviour):
	pass
@UTTCGen
class TravelDestination(MonoBehaviour):
	MoveToPositionOnArrival : bool
	RemoveOverlayImageOnArrival : bool
	target : Vector3f
	areaName : str
	onArrival : object # XXX: Fallback of UnityEvent
@UTTCGen
class Teleporter(MonoBehaviour):
	MoveToPositionOnArrival : bool
	RemoveOverlayImageOnArrival : bool
	target : Vector3f
	areaName : str
	onArrival : object # XXX: Fallback of UnityEvent
	destination : PPtr[TravelDestination]
	onActivation : object # XXX: Fallback of UnityEvent
@UTTCGen
class TequilaUIStenciliere(MonoBehaviour):
	prepassMaterial : PPtr[Material]
	colorOverride : bool
	colorCustom : ColorRGBA
@UTTCGen
class TransitionEntity(MonoBehaviour):
	_interactionRadius : float
	outlinesOverride : bool
	conversation : str
	themesong : str
	area : str
	destination : str
	IsLocked : bool
	kimSwitches : List[KimSwitchBoolean]
@UTTCGen
class ZoomAnimator(MonoBehaviour):
	startScale : Vector3f
	startPos : Vector3f
	length : float
