# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.HUD

from .... import *
from .... import PortraitVisualizer

@UTTCGen
class PageSystemHUDPortraitsAnimator(MonoBehaviour):
	showPortraitsButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	companionPortrait : PPtr[RectTransform]
	parentRectTransform : PPtr[RectTransform]
	healingPanelRectTransform : PPtr[RectTransform]
	arrowRect : PPtr[RectTransform]
	arrowImage : PPtr[Image]
	arrowOpenedColor : ColorRGBA
	arrowClosedColor : ColorRGBA
@UTTCGen
class PartyVisualizerPageSystem(MonoBehaviour):
	tequilaPortrait : PPtr[PortraitVisualizer]
	companionPortrait : PPtr[PortraitVisualizer]
	portraitVisualizers : List[PPtr[PortraitVisualizer]]
