# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for LocalizationCustomSystem

from .. import *

@UTTCGen
class DyslexicFontConfiguration(MonoBehaviour):
	toggle : PPtr[object] # XXX: Fallback of PPtr<Toggle>
@UTTCGen
class FontTranslationString(MonoBehaviour):
	term : str
@UTTCGen
class I2LocalizeButton(MonoBehaviour):
	mTerm : str
	mTermSecondary : str
	PrimaryTermModifier : int
	SecondaryTermModifier : int
	TermPrefix : str
	TermSuffix : str
	LocalizeOnAwake : bool
	IgnoreRTL : bool
	MaxCharactersInRTL : int
	IgnoreNumbersInRTL : bool
	CorrectAlignmentForRTL : bool
	AppendReversedPrefixForRTL : bool
	AddSpacesToJoinedLanguages : bool
	AllowLocalizedParameters : bool
	AllowParameters : bool
	TranslatedObjects : List[PPtr[Object]]
	LocalizeEvent : object # XXX: Fallback of UnityEvent
	AlwaysForceLocalize : bool
	LocalizeCallBack : object # XXX: Fallback of EventCallback
	mGUI_ShowReferences : bool
	mGUI_ShowTems : bool
	mGUI_ShowCallback : bool
	mLocalizeTarget : PPtr[object] # XXX: Fallback of PPtr<ILocalizeTarget>
	mLocalizeTargetName : str
	defaultButtonTerm : str
	highlightedTerm : str
	pressedTerm : str
	selectedTerm : str
	disabledTerm : str
	localizeHighlightedSprite : bool
	localizePressedSprite : bool
	localizeSelectedSprite : bool
	localizeDisabledSprite : bool
	button : PPtr[object] # XXX: Fallback of PPtr<Button>
	image : PPtr[Image]
@UTTCGen
class I2LocalizeDropdown(MonoBehaviour):
	_Terms : List[str]
	Modifier : int
@UTTCGen
class I2LocalizeFlipClock(MonoBehaviour):
	mTerm : str
	mTermSecondary : str
	PrimaryTermModifier : int
	SecondaryTermModifier : int
	TermPrefix : str
	TermSuffix : str
	LocalizeOnAwake : bool
	IgnoreRTL : bool
	MaxCharactersInRTL : int
	IgnoreNumbersInRTL : bool
	CorrectAlignmentForRTL : bool
	AppendReversedPrefixForRTL : bool
	AddSpacesToJoinedLanguages : bool
	AllowLocalizedParameters : bool
	AllowParameters : bool
	TranslatedObjects : List[PPtr[Object]]
	LocalizeEvent : object # XXX: Fallback of UnityEvent
	AlwaysForceLocalize : bool
	LocalizeCallBack : object # XXX: Fallback of EventCallback
	mGUI_ShowReferences : bool
	mGUI_ShowTems : bool
	mGUI_ShowCallback : bool
	mLocalizeTarget : PPtr[object] # XXX: Fallback of PPtr<ILocalizeTarget>
	mLocalizeTargetName : str
@UTTCGen
class LocalizationManager(MonoBehaviour):
	DebugLogs : bool
@UTTCGen
class LocalizationOption(MonoBehaviour):
	displayedOption : str
	englishLanguageName : str
@UTTCGen
class SwitchableLocalizationSettingsOption(MonoBehaviour):
	dropdown : PPtr[object] # XXX: Fallback of PPtr<TMP_Dropdown>
	lastOption : LocalizationOption
@UTTCGen
class LocalizationSettingsOption(MonoBehaviour):
	switchableLocalizationSettingsOption : PPtr[SwitchableLocalizationSettingsOption]
	lastOption : LocalizationOption
@UTTCGen
class LocalizationUtils(MonoBehaviour):
	pass
@UTTCGen
class TranslationShadows(MonoBehaviour):
	language : str
	enabled : bool
@UTTCGen
class LocalizedShadows(MonoBehaviour):
	translationList : List[TranslationShadows]
@UTTCGen
class LocalizedTextFormatter(MonoBehaviour):
	useCharacterWrappingInKorean : bool
@UTTCGen
class TranslationFontBestFit(MonoBehaviour):
	language : str
	minFontSize : int
	maxFontSize : int
@UTTCGen
class LocalizeFontBestFit(MonoBehaviour):
	translationList : List[TranslationFontBestFit]
@UTTCGen
class TranslationFontSize(MonoBehaviour):
	language : str
	fontSize : int
@UTTCGen
class LocalizeFontSize(MonoBehaviour):
	translationList : List[TranslationFontSize]
@UTTCGen
class LocalizeFontSizeTMPro(MonoBehaviour):
	translationList : List[TranslationFontSize]
@UTTCGen
class TranslationLetterSpacing(MonoBehaviour):
	language : str
	letterSpacing : float
@UTTCGen
class LocalizeLetterSpacing(MonoBehaviour):
	translationList : List[TranslationLetterSpacing]
@UTTCGen
class TranslationLineSpacing(MonoBehaviour):
	language : str
	lineSpacing : int
@UTTCGen
class LocalizeLineSpacing(MonoBehaviour):
	translationList : List[TranslationLineSpacing]
@UTTCGen
class TranslationSuffix(MonoBehaviour):
	language : str
	suffix : str
@UTTCGen
class LocalizePrefix(MonoBehaviour):
	translationList : List[TranslationSuffix]
@UTTCGen
class TranslationTextOffset(MonoBehaviour):
	language : str
	offset : Vector2f
@UTTCGen
class LocalizeRectTransformOffset(MonoBehaviour):
	translationList : List[TranslationTextOffset]
@UTTCGen
class TranslationFloat(MonoBehaviour):
	floatValues : List[float]
	languagesNames : List[str]
@UTTCGen
class LocalizeRectTransformSize(MonoBehaviour):
	localizedWidth : TranslationFloat
	localizedHeight : TranslationFloat
@UTTCGen
class LocalizeSuffix(MonoBehaviour):
	translationList : List[TranslationSuffix]
@UTTCGen
class LocalizeTextOffset(MonoBehaviour):
	translationList : List[TranslationTextOffset]
@UTTCGen
class TranslationMargins(MonoBehaviour):
	language : str
	margins : Vector2f
@UTTCGen
class LocalizeVerticalMargins(MonoBehaviour):
	translationList : List[TranslationMargins]
@UTTCGen
class MaterialTranslationString(MonoBehaviour):
	term : str
@UTTCGen
class SmoothLanguageSwitch(MonoBehaviour):
	fadeOutTime : float
	fadeInTime : float
	snapToggle : bool
@UTTCGen
class TermsUtils(MonoBehaviour):
	pass
@UTTCGen
class TranslationString(MonoBehaviour):
	Term : str
@UTTCGen
class TranslationTestableFloat(MonoBehaviour):
	floatValues : List[float]
	languagesNames : List[str]
