# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages.Common.Charsheet

from .... import *
from ....Sunshine.Metric import Modifiable
from ....Sunshine.Metric import Modifier
from ....DiscoPages.Elements.Charsheet import PageSystemStatPanel
from .... import SegmentIndicator
from ....PagesSystem import SkillPortraitAnimatorHelperPageSystem
from .... import SkillPortraitOverviewPanel
from ....DiscoPages.Elements import SkillPortraitPanelPageSystem
from ....DiscoPages.Elements.Common import SwipeDetector
from .... import SwipeUIElementSelectionController
from .... import TabSwitchAnimationController
from ....Charsheet import TranslationScriptable

@UTTCGen
class CharsheetPage(MonoBehaviour):
	stats : List[PPtr[PageSystemStatPanel]]
	portraits : List[PPtr[SkillPortraitPanelPageSystem]]
	maximizeButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	minimizeButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	swipeDetectors : List[SwipeDetector]
@UTTCGen
class SkillInfoNavigationParameters(MonoBehaviour):
	titleText : str
	shortDescriptionText : str
	longDescriptionText : str
	charsheetPage : PPtr[CharsheetPage]
	portrait : PPtr[SkillPortraitPanelPageSystem]
@UTTCGen
class SkillInfoPage(MonoBehaviour):
	skillOverviewNavigateButtons : List[object] # XXX: Fallback of Button[]
	titleText : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	shortDescription : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	longDescription : PPtr[object] # XXX: Fallback of PPtr<TextMeshProUGUI>
	tabSwitchAnimationController : PPtr[TabSwitchAnimationController]
@UTTCGen
class SkillOverviewNavigationParameters(MonoBehaviour):
	modifiable : Modifiable
	portraitPanel : PPtr[SkillPortraitPanelPageSystem]
	charsheetPage : PPtr[CharsheetPage]
@UTTCGen
class SkillOverviewPage(MonoBehaviour):
	skillInfoNavigateButtons : List[object] # XXX: Fallback of Button[]
	portraitSkillPipIndicator : PPtr[SegmentIndicator]
	skillPortraitAnimatorHelper : PPtr[SkillPortraitAnimatorHelperPageSystem]
	leftArrowButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	rightArrowButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	confirmButton : PPtr[object] # XXX: Fallback of PPtr<Button>
	portraitOverviewPanel : PPtr[SkillPortraitOverviewPanel]
	leftPortraitOverviewPanel : PPtr[SkillPortraitOverviewPanel]
	rightPortraitOverviewPanel : PPtr[SkillPortraitOverviewPanel]
	tabSwitchAnimationController : PPtr[TabSwitchAnimationController]
	swipeAnimatorController : PPtr[SwipeUIElementSelectionController]
@UTTCGen
class SkillOverviewPageLabelConfigurator(MonoBehaviour):
	labelsSettings : List[TranslationScriptable]
