# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for FontSizeProfiles

from .. import *
from ..FontSizeProfiles.ViewProfiles import ArchetypeSelectionProfile
from ..FontSizeProfiles.BuildParts import AutoTextElementSettings
from ..FontSizeProfiles.ViewProfiles import CharsheetProfile
from ..FontSizeProfiles.ViewProfiles import CollageModeProfile
from ..FontSizeProfiles.ViewProfiles import ControllerHelpMenuProfile
from ..FontSizeProfiles.ViewProfiles import InfoPanelProfile
from ..FontSizeProfiles.ViewProfiles import InventoryProfile
from ..FontSizeProfiles.ViewProfiles import JournalProfile
from ..FontSizeProfiles.ViewProfiles import LeftStatsHealthBonusesPanelProfile
from ..FontSizeProfiles.ViewProfiles import MainMenuProfile
from ..FontSizeProfiles.ViewProfiles import MapProfile
from ..FontSizeProfiles.BuildParts import MonoBehaviourEnableSettings
from ..FontSizeProfiles.ViewProfiles import NewspaperEndingProfile
from ..FontSizeProfiles.ViewProfiles import OptionsProfile
from ..FontSizeProfiles.BuildParts import RectElementHeightSettings
from ..FontSizeProfiles.BuildParts import RectElementHorizontalSettings
from ..FontSizeProfiles.BuildParts import RectElementSettings
from ..FontSizeProfiles.ViewProfiles import SaveLoadProfile
from ..FontSizeProfiles.BuildParts import TextElementSettings
from ..FontSizeProfiles.ViewProfiles import ThoughtCabinetProfile
from ..FontSizeProfiles.ViewProfiles import ThoughtSplashScreenProfile

@UTTCGen
class AutoFontSizePerLanguage(MonoBehaviour):
	languageCode : str
	minFontSize : int
	maxFontSize : int
@UTTCGen
class DictionaryExtensions(MonoBehaviour):
	pass
@UTTCGen
class FontSizePerLanguage(MonoBehaviour):
	languageCode : str
	fontSize : int
@UTTCGen
class LayoutProfile(MonoBehaviour):
	proflieName : str
	mainMenuProfile : MainMenuProfile
	optionsProfile : OptionsProfile
	controllerHelpMenuProfile : ControllerHelpMenuProfile
	infoPanelProfile : InfoPanelProfile
	saveLoadProfile : SaveLoadProfile
	archetypeSelectionProfile : ArchetypeSelectionProfile
	charsheetProfile : CharsheetProfile
	inventoryProfile : InventoryProfile
	leftStatsHealthBonusesPanelProfile : LeftStatsHealthBonusesPanelProfile
	thoughtCabinetProfile : ThoughtCabinetProfile
	thoughtSplashScreenProfile : ThoughtSplashScreenProfile
	journalProfile : JournalProfile
	mapProfile : MapProfile
	newspaperEndingProfile : NewspaperEndingProfile
	collageModeProfile : CollageModeProfile
@UTTCGen
class LayoutProfileChanger(MonoBehaviour):
	profiles : List[PPtr[LayoutProfile]]
	currentlySelectedProfile : PPtr[LayoutProfile]
@UTTCGen
class StringHelpers(MonoBehaviour):
	pass
@UTTCGen
class SwitchLayoutProfileChange(MonoBehaviour):
	pass
@UTTCGen
class ViewProfilesUtils(MonoBehaviour):
	pass
