# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for TwitchIntegration.Debug

from ... import *
from ... import Text

@UTTCGen
class TwitchDebug(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	resultLabel : PPtr[Text]
@UTTCGen
class TwitchDebugMeditationPoll(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	resultLabel : PPtr[Text]
	stateLabel : PPtr[Text]
@UTTCGen
class TwitchDebugPoll(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	resultLabel : PPtr[Text]
	stateLabel : PPtr[Text]
	pollResultLabel : PPtr[Text]
@UTTCGen
class TwitchDebugRegisterSecretKey(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	resultLabel : PPtr[Text]
	secretKeyField : PPtr[object] # XXX: Fallback of PPtr<InputField>
	showServerType : PPtr[object] # XXX: Fallback of PPtr<Graphic>
	serverTypeLabel : PPtr[Text]
@UTTCGen
class TwitchDebugUpdateGameData(MonoBehaviour):
	canvasGroup : PPtr[CanvasGroup]
	resultLabel : PPtr[Text]
