# fmt: off
# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.Journal

from .... import *

@UTTCGen('DiscoPages.Elements.Journal.PageSystemJournalTasksScroll', [{"m_Type": "MonoBehaviour", "m_Name": "Base", "m_Level": 0, "m_MetaFlag": 0}, {"m_Type": "PPtr<GameObject>", "m_Name": "m_GameObject", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "m_FileID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt64", "m_Name": "m_PathID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "UInt8", "m_Name": "m_Enabled", "m_Level": 1, "m_MetaFlag": 16384}, {"m_Type": "PPtr<MonoScript>", "m_Name": "m_Script", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "m_FileID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt64", "m_Name": "m_PathID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "string", "m_Name": "m_Name", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "Array", "m_Name": "Array", "m_Level": 2, "m_MetaFlag": 16384}, {"m_Type": "int", "m_Name": "size", "m_Level": 3, "m_MetaFlag": 0}, {"m_Type": "char", "m_Name": "data", "m_Level": 3, "m_MetaFlag": 0}, {"m_Type": "PPtr<GameObject>", "m_Name": "taskDayPrefab", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "m_FileID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt64", "m_Name": "m_PathID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "PPtr<RectTransform>", "m_Name": "upperPart", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "m_FileID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt64", "m_Name": "m_PathID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "PPtr<VerticalLayoutGroup>", "m_Name": "content", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "m_FileID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt64", "m_Name": "m_PathID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt32", "m_Name": "topPadding", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "SInt32", "m_Name": "tmpTaskDayMockupCount", "m_Level": 1, "m_MetaFlag": 0}])
class PageSystemJournalTasksScroll(MonoBehaviour):
	taskDayPrefab : PPtr[GameObject]
	upperPart : PPtr[RectTransform]
	content : PPtr[object] # XXX: Fallback of PPtr<VerticalLayoutGroup>
	topPadding : int
	tmpTaskDayMockupCount : int
