# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.Journal

from .... import *

@UTTCGen
class PageSystemJournalTasksScroll(MonoBehaviour):
	taskDayPrefab : PPtr[GameObject]
	upperPart : PPtr[RectTransform]
	content : PPtr[object] # XXX: Fallback of PPtr<VerticalLayoutGroup>
	topPadding : int
	tmpTaskDayMockupCount : int
