# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for IOSCamera

from .. import *
from .. import Camera
from .. import ScreenPointToRay

@UTTCGen
class iOSCameraPositionController(MonoBehaviour):
	screenPointToRay : PPtr[ScreenPointToRay]
@UTTCGen
class iOSZoomController(MonoBehaviour):
	zoomValue : float
	zoomLimitsExternal : Vector2f
	zoomLimitsInternals : Vector2f
	zoomSpeed : float
	zoomScrollWheelSpeed : float
@UTTCGen
class iOSCameraControllerTest(MonoBehaviour):
	camera : PPtr[Camera]
	zoomController : PPtr[iOSZoomController]
	positionController : PPtr[iOSCameraPositionController]
@UTTCGen
class iOSCameraLock(MonoBehaviour):
	pass
@UTTCGen
class iOSDialogCameraMinature(MonoBehaviour):
	zoomController : PPtr[iOSZoomController]
	cameraReference : PPtr[Camera]
@UTTCGen
class OnFloatChangedEvent(MonoBehaviour):
	pass
