# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for UnityEngine.UI.Extensions

from .... import *

@UTTCGen
class UIScrollToSelection(MonoBehaviour):
	scrollDirection : int
	scrollSpeed : float
	cancelScrollOnInput : bool
	cancelScrollKeycodes : List[int]
