# fmt: off
# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for UnityEngine.UI.Extensions

from .... import *

@UTTCGen('UnityEngine.UI.Extensions.UIScrollToSelection', [{"m_Type": "MonoBehaviour", "m_Name": "Base", "m_Level": 0, "m_MetaFlag": 0}, {"m_Type": "PPtr<GameObject>", "m_Name": "m_GameObject", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "m_FileID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt64", "m_Name": "m_PathID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "UInt8", "m_Name": "m_Enabled", "m_Level": 1, "m_MetaFlag": 16384}, {"m_Type": "PPtr<MonoScript>", "m_Name": "m_Script", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "m_FileID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "SInt64", "m_Name": "m_PathID", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "string", "m_Name": "m_Name", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "Array", "m_Name": "Array", "m_Level": 2, "m_MetaFlag": 16384}, {"m_Type": "int", "m_Name": "size", "m_Level": 3, "m_MetaFlag": 0}, {"m_Type": "char", "m_Name": "data", "m_Level": 3, "m_MetaFlag": 0}, {"m_Type": "SInt32", "m_Name": "scrollDirection", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "float", "m_Name": "scrollSpeed", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "bool", "m_Name": "cancelScrollOnInput", "m_Level": 1, "m_MetaFlag": 16384}, {"m_Type": "List`1", "m_Name": "cancelScrollKeycodes", "m_Level": 1, "m_MetaFlag": 0}, {"m_Type": "Array", "m_Name": "Array", "m_Level": 2, "m_MetaFlag": 0}, {"m_Type": "int", "m_Name": "size", "m_Level": 3, "m_MetaFlag": 0}, {"m_Type": "SInt32", "m_Name": "data", "m_Level": 3, "m_MetaFlag": 0}])
class UIScrollToSelection(MonoBehaviour):
	scrollDirection : int
	scrollSpeed : float
	cancelScrollOnInput : bool
	cancelScrollKeycodes : List[int]
