# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Unseen

from ... import *
from ... import Camera

@UTTCGen
class ActiveCurve(MonoBehaviour):
	pass
@UTTCGen
class Unseen(MonoBehaviour):
	focus : float
	saturation : float
	brightness : float
	aberration : float
@UTTCGen
class ActiveValues(MonoBehaviour):
	values : Unseen
@UTTCGen
class BaseValues(MonoBehaviour):
	values : Unseen
@UTTCGen
class CameraScript(MonoBehaviour):
	aberrationHueShift : float
	aberrationColor : ColorRGBA
	renderCamera : PPtr[Camera]
	unseenShader : PPtr[Shader]
	unseenReplacementShader : PPtr[Shader]
	unseenMaterial : PPtr[Material]
	renderTexture : PPtr[RenderTexture]
	downsample : int
	blurShader : PPtr[Shader]
	blurMaterial : PPtr[Material]
	blurDownsample : int
	blurSize : float
	blurIterations : int
	blurType : int
@UTTCGen
class InactiveCurve(MonoBehaviour):
	pass
@UTTCGen
class InactiveValues(MonoBehaviour):
	values : Unseen
@UTTCGen
class Observer(MonoBehaviour):
	pass
@UTTCGen
class ShaderScript(MonoBehaviour):
	pass
@UTTCGen
class StatusCurve(MonoBehaviour):
	pass
@UTTCGen
class UnseenValues(MonoBehaviour):
	values : Unseen
@UTTCGen
class Zone(MonoBehaviour):
	unseenZoneShader : PPtr[Shader]
	zoneMaterial : PPtr[Material]
	_status : int
