# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Pages

from .. import *

@UTTCGen
class DiscoPage(MonoBehaviour):
	pass
@UTTCGen
class PagesTest(MonoBehaviour):
	dialogueButton : PPtr[object] # XXX: Fallback of PPtr<Button>
@UTTCGen
class SubPage(MonoBehaviour):
	pass
