# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for DiscoPages.Elements.Dialogue

from .... import *
from .... import LogRenderer
from .... import PeekLayout

@UTTCGen
class ContinueResponseTogglePageSystem(MonoBehaviour):
	showDebugInfo : bool
	reactionsPeekLayout : PPtr[PeekLayout]
	optionsPanel : PPtr[RectTransform]
	continueButton : PPtr[RectTransform]
	delaySeconds : float
@UTTCGen
class ConversationLoggerPageSystem(MonoBehaviour):
	_ShowLog : bool
	logRenderer : PPtr[LogRenderer]
	viewportFocus : Vector2f
	inSequence : bool
	processContinueButtonHotkey : bool
@UTTCGen
class DraggableResponse(MonoBehaviour):
	draggableResponsePrefab : PPtr[RectTransform]
	textFields : List[object] # XXX: Fallback of TextMeshProUGUI[]
	responseButton : PPtr[object] # XXX: Fallback of PPtr<Button>
