# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Metric

from ... import *
from ... import HudHeldButton
from ... import ItemType
from ... import SunshineCharacterTemplate
from ... import SunshineClockTime
from ...LocalizationCustomSystem import TranslationString

@UTTCGen
class Modifier(MonoBehaviour):
	type : int
	skillType : int
@UTTCGen
class Ability(MonoBehaviour):
	dirty : bool
	value : int
	valueWithoutPerceptionsSubSkills : int
	damageValue : int
	maximumValue : int
	calculatedAbility : int
	rankValue : int
	hasAdvancement : bool
	isSignature : bool
	modifiers : List[Modifier]
	abilityType : int
@UTTCGen
class AbilityType(MonoBehaviour):
	value__ : int
@UTTCGen
class CharacterEffect(MonoBehaviour):
	effect : int
	intrinsic : bool
	abilityType : int
	skillType : int
	parameter : int
	stringParameter : str
	stringParameterTerm : TranslationString
	quipLine : str
	quipLineTerm : TranslationString
@UTTCGen
class Duration(MonoBehaviour):
	duration : int
	startDay : int
	startTime : int
@UTTCGen
class CharacterBuff(MonoBehaviour):
	cause : int
	effects : List[CharacterEffect]
	duration : Duration
@UTTCGen
class Skill(MonoBehaviour):
	dirty : bool
	value : int
	valueWithoutPerceptionsSubSkills : int
	damageValue : int
	maximumValue : int
	calculatedAbility : int
	rankValue : int
	hasAdvancement : bool
	isSignature : bool
	modifiers : List[Modifier]
	skillType : int
	abilityType : int
@UTTCGen
class CharacterSheet(MonoBehaviour):
	intellect : Ability
	psyche : Ability
	fysique : Ability
	motorics : Ability
	logic : Skill
	encyclopedia : Skill
	rhetoric : Skill
	drama : Skill
	conceptualization : Skill
	visualCalculus : Skill
	volition : Skill
	inlandEmpire : Skill
	empathy : Skill
	authority : Skill
	suggestion : Skill
	espritDeCorps : Skill
	physicalInstrument : Skill
	electrochemistry : Skill
	endurance : Skill
	halfLight : Skill
	painThreshold : Skill
	shivers : Skill
	handEyeCoordination : Skill
	perception : Skill
	reaction : Skill
	savoirFaire : Skill
	interfacing : Skill
	composure : Skill
	dirty : bool
@UTTCGen
class ThoughtCabinetProject(MonoBehaviour):
	fresh : bool
	researchTimeLeft : int
	researchTime : int
	researchEffects : List[CharacterEffect]
	completionEffects : List[CharacterEffect]
	discoverTime : SunshineClockTime
	voiceoverTerm : str
	displayNameTerm : TranslationString
	descriptionTerm : TranslationString
	completionDescriptionTerm : TranslationString
@UTTCGen
class CharacterSheetFactory(MonoBehaviour):
	testArchetype : PPtr[SunshineCharacterTemplate]
	thcProject : PPtr[ThoughtCabinetProject]
@UTTCGen
class CharacterThoughts(MonoBehaviour):
	discoveredThoughts : List[PPtr[ThoughtCabinetProject]]
@UTTCGen
class CheckBonus(MonoBehaviour):
	bonus : int
	fallbackExplanation : str
	localizedExplanation : TranslationString
@UTTCGen
class CheckForced(MonoBehaviour):
	value__ : int
@UTTCGen
class CheckModifier(MonoBehaviour):
	bonus : int
	fallbackExplanation : str
	localizedExplanation : TranslationString
	expression : str
@UTTCGen
class CheckResult(MonoBehaviour):
	explanation : str
	checkType : int
	skillType : int
	abilityBase : int
	skillBase : int
	die1 : int
	die2 : int
	baseTarget : int
	IsSuccess : bool
	isLocked : bool
	forced : int
@UTTCGen
class CheckType(MonoBehaviour):
	value__ : int
@UTTCGen
class Difficulty(MonoBehaviour):
	value__ : int
@UTTCGen
class DifficultyUtil(MonoBehaviour):
	pass
@UTTCGen
class EffectType(MonoBehaviour):
	value__ : int
@UTTCGen
class InventoryItemExtension(MonoBehaviour):
	pass
@UTTCGen
class InventoryViewData(MonoBehaviour):
	pass
@UTTCGen
class Modifiable(MonoBehaviour):
	dirty : bool
	value : int
	valueWithoutPerceptionsSubSkills : int
	damageValue : int
	maximumValue : int
	calculatedAbility : int
	rankValue : int
	hasAdvancement : bool
	isSignature : bool
	modifiers : List[Modifier]
@UTTCGen
class ModifierType(MonoBehaviour):
	value__ : int
@UTTCGen
class NumberEffect(MonoBehaviour):
	intristic : bool
	amount : int
	explanation : str
@UTTCGen
class PlayerCharacter(MonoBehaviour):
	xpAmount : int
	level : int
	skillPoints : int
	NewPointsToSpend : bool
	money : int
@UTTCGen
class PlayerCharacterHealingPools(MonoBehaviour):
	pass
@UTTCGen
class RewardType(MonoBehaviour):
	value__ : int
@UTTCGen
class SkillCapType(MonoBehaviour):
	value__ : int
@UTTCGen
class SkillType(MonoBehaviour):
	value__ : int
@UTTCGen
class SkillTypeExtension(MonoBehaviour):
	pass
@UTTCGen
class SunshineRoller(MonoBehaviour):
	pass
@UTTCGen
class ThoughtState(MonoBehaviour):
	value__ : int
@UTTCGen
class XPUtil(MonoBehaviour):
	pass
