# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for IntroSystem

from .. import *
from ..FortressOccident import ApplicationManager
from ..Sunshine import AreaManager
from .. import LobbyFade
from .. import VideoStream

@UTTCGen
class ElementType(MonoBehaviour):
	value__ : int
@UTTCGen
class FadeScreen(MonoBehaviour):
	pass
@UTTCGen
class IntroElement(MonoBehaviour):
	willFadeIn : bool
	willFadeOut : bool
	canBeSkipped : bool
	willCutFadeOutAtSkip : bool
	fadeInDuration : float
	fadeOutDuration : float
	displayDuration : float
@UTTCGen
class IntroManager(MonoBehaviour):
	TurnedOn : bool
	introCanvas : PPtr[GameObject]
	fadeScreen : PPtr[FadeScreen]
	videoPlayer : PPtr[VideoPlayer]
	backgroundImage : PPtr[Image]
	introImage : PPtr[Image]
	applicationManager : PPtr[ApplicationManager]
	lobbyFade : PPtr[LobbyFade]
	introVideoStream : PPtr[VideoStream]
	initSceneLoaded : PPtr[AreaManager]
	introElements : List[PPtr[IntroElement]]
	objectsToActivate : List[PPtr[GameObject]]
	delayBetweenIntroElements : float
@UTTCGen
class IntroSprite(MonoBehaviour):
	willFadeIn : bool
	willFadeOut : bool
	canBeSkipped : bool
	willCutFadeOutAtSkip : bool
	fadeInDuration : float
	fadeOutDuration : float
	displayDuration : float
	sprite : PPtr[Sprite]
@UTTCGen
class IntroVideo(MonoBehaviour):
	willFadeIn : bool
	willFadeOut : bool
	canBeSkipped : bool
	willCutFadeOutAtSkip : bool
	fadeInDuration : float
	fadeOutDuration : float
	displayDuration : float
	video : PPtr[VideoClip]
