# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for statistics

from .. import *

@UTTCGen
class ArticyXmlStatistics(MonoBehaviour):
	pass
@UTTCGen
class ConditionComparer(MonoBehaviour):
	pass
@UTTCGen
class ConnectionComparer(MonoBehaviour):
	pass
@UTTCGen
class DialogueEntry(MonoBehaviour):
	Id : int
	Title : str
	DialogueText : str
	UserScript : str
	Condition : str
	NodeType : int
@UTTCGen
class Conversation(MonoBehaviour):
	Id : int
	Title : str
	Description : str
	References : List[str]
	Entries : List[DialogueEntry]
	ConversationType : int
	Instruction : str
@UTTCGen
class ConversationType(MonoBehaviour):
	value__ : int
@UTTCGen
class DataExporter(MonoBehaviour):
	ntwtfDD : PPtr[object] # XXX: Fallback of PPtr<DialogueDatabase>
@UTTCGen
class Dialogue(MonoBehaviour):
	Conversations : List[Conversation]
@UTTCGen
class DialogueComparer(MonoBehaviour):
	pass
@UTTCGen
class DialogueFragmentComparer(MonoBehaviour):
	pass
@UTTCGen
class DialogueGraph(MonoBehaviour):
	pass
@UTTCGen
class DialogueGraphBacktracker(MonoBehaviour):
	pass
@UTTCGen
class DialogueGraphXML(MonoBehaviour):
	pass
@UTTCGen
class DialogueSanityChecks(MonoBehaviour):
	pass
@UTTCGen
class DialogueStatisticsCollector(MonoBehaviour):
	pass
@UTTCGen
class DialogueVersionComparer(MonoBehaviour):
	File1Location : str
	File2Location : str
@UTTCGen
class DoorStatisticsCollector(MonoBehaviour):
	pass
@UTTCGen
class DuplicateBasicEntityFinder(MonoBehaviour):
	pass
@UTTCGen
class ElementComparer(MonoBehaviour):
	pass
@UTTCGen
class FeatureComparer(MonoBehaviour):
	pass
@UTTCGen
class FieldHolder(MonoBehaviour):
	pass
@UTTCGen
class HierarchyComparer(MonoBehaviour):
	pass
@UTTCGen
class InteractablesStatisticsCollector(MonoBehaviour):
	pass
@UTTCGen
class Item(MonoBehaviour):
	Id : int
	Name : str
	Group : str
	Dialogue : str
	Container : str
@UTTCGen
class Items(MonoBehaviour):
	list : List[Item]
@UTTCGen
class ItemStatisticsCollector(MonoBehaviour):
	pass
@UTTCGen
class ItemUtil(MonoBehaviour):
	pass
@UTTCGen
class JournalStatisticsCollector(MonoBehaviour):
	pass
@UTTCGen
class LocalizableTextComparer(MonoBehaviour):
	pass
@UTTCGen
class NodeType(MonoBehaviour):
	value__ : int
@UTTCGen
class OrbsWOCameraMarkers(MonoBehaviour):
	pass
@UTTCGen
class PinComparer(MonoBehaviour):
	pass
@UTTCGen
class TaskStatisticsCollector(MonoBehaviour):
	pass
@UTTCGen
class TaskXPCollector(MonoBehaviour):
	pass
@UTTCGen
class TranslationDataParser(MonoBehaviour):
	XMLFileLocation : str
	CSVFileLocation : str
	DialogueArticyID : str
@UTTCGen
class VariableComparer(MonoBehaviour):
	pass
@UTTCGen
class VariableStatisticsCollector(MonoBehaviour):
	pass
@UTTCGen
class WordCounter(MonoBehaviour):
	pass
