# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for PSNSample

from .. import *

@UTTCGen
class GamePad(MonoBehaviour):
	playerId : int
@UTTCGen
class IScreen(MonoBehaviour):
	pass
@UTTCGen
class MenuLayout(MonoBehaviour):
	pass
@UTTCGen
class MenuStack(MonoBehaviour):
	pass
@UTTCGen
class Notifications(MonoBehaviour):
	pass
@UTTCGen
class OnScreenLog(MonoBehaviour):
	pass
@UTTCGen
class SonyMessages(MonoBehaviour):
	pass
@UTTCGen
class SonyNpMain(MonoBehaviour):
	iconRender : PPtr[MeshRenderer]
@UTTCGen
class SonySessionSignalling(MonoBehaviour):
	pass
@UTTCGen
class SonyTitleCloudStorage(MonoBehaviour):
	pass
@UTTCGen
class User(MonoBehaviour):
	pass
