# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Hack

from ... import *

@UTTCGen
class KimKitsuragi(MonoBehaviour):
	isRemovingPissJacket : bool
	GoodMorningBarkOnNextEncounter : bool
@UTTCGen
class Kubujuss(MonoBehaviour):
	pass
