# Auto-generated by https://github.com/mos9527/UnityPyTypetreeCodegen
# Python definition for Sunshine.Feld

from ... import *

@UTTCGen
class FeldView(MonoBehaviour):
	value__ : int
@UTTCGen
class FeldViewController(MonoBehaviour):
	currentView : int
@UTTCGen
class IntroFeldViewController(MonoBehaviour):
	currentView : int
